# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CeusTool3d/exportData.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_exportData(object):
    def setupUi(self, exportData):
        exportData.setObjectName("exportData")
        exportData.resize(1175, 749)
        exportData.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.widget = QtWidgets.QWidget(exportData)
        self.widget.setGeometry(QtCore.QRect(0, 0, 341, 751))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.widget.setObjectName("widget")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.label.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(-60, 50, 191, 51))
        self.label_2.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.imagePathInput = QtWidgets.QLabel(self.frame)
        self.imagePathInput.setGeometry(QtCore.QRect(100, 50, 241, 51))
        self.imagePathInput.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.imagePathInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.imagePathInput.setObjectName("imagePathInput")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);;\n"
"    border: 1px solid black;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(0, 40, 341, 51))
        self.label_4.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.frame_4 = QtWidgets.QFrame(self.widget)
        self.frame_4.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.frame_4.setStyleSheet("QFrame {\n"
"    background-color:  rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.label_7.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.frame_5 = QtWidgets.QFrame(self.widget)
        self.frame_5.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.frame_5.setStyleSheet("QFrame {\n"
"    background-color:  rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.label_8.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.frame_3 = QtWidgets.QFrame(exportData)
        self.frame_3.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.frame_3.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.label_6.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.backButton = QtWidgets.QPushButton(exportData)
        self.backButton.setGeometry(QtCore.QRect(10, 690, 131, 41))
        self.backButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.backButton.setObjectName("backButton")
        self.selectDataLabel = QtWidgets.QLabel(exportData)
        self.selectDataLabel.setGeometry(QtCore.QRect(530, 60, 431, 131))
        self.selectDataLabel.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.selectDataLabel.setTextFormat(QtCore.Qt.AutoText)
        self.selectDataLabel.setScaledContents(False)
        self.selectDataLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.selectDataLabel.setWordWrap(True)
        self.selectDataLabel.setObjectName("selectDataLabel")
        self.appendFileOptionButton = QtWidgets.QPushButton(exportData)
        self.appendFileOptionButton.setGeometry(QtCore.QRect(600, 320, 301, 51))
        self.appendFileOptionButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.appendFileOptionButton.setObjectName("appendFileOptionButton")
        self.clearAppendFileButton = QtWidgets.QPushButton(exportData)
        self.clearAppendFileButton.setGeometry(QtCore.QRect(750, 380, 131, 41))
        self.clearAppendFileButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clearAppendFileButton.setObjectName("clearAppendFileButton")
        self.appendFileLabel = QtWidgets.QLabel(exportData)
        self.appendFileLabel.setGeometry(QtCore.QRect(610, 270, 271, 51))
        self.appendFileLabel.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.appendFileLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.appendFileLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.appendFileLabel.setObjectName("appendFileLabel")
        self.chooseAppendFileButton = QtWidgets.QPushButton(exportData)
        self.chooseAppendFileButton.setGeometry(QtCore.QRect(612, 380, 131, 41))
        self.chooseAppendFileButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.chooseAppendFileButton.setObjectName("chooseAppendFileButton")
        self.appendFilePath = QtWidgets.QLineEdit(exportData)
        self.appendFilePath.setGeometry(QtCore.QRect(640, 330, 201, 31))
        self.appendFilePath.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.appendFilePath.setObjectName("appendFilePath")
        self.newFileOptionButton = QtWidgets.QPushButton(exportData)
        self.newFileOptionButton.setGeometry(QtCore.QRect(600, 430, 301, 51))
        self.newFileOptionButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.newFileOptionButton.setObjectName("newFileOptionButton")
        self.newFolderPathInput = QtWidgets.QLineEdit(exportData)
        self.newFolderPathInput.setGeometry(QtCore.QRect(640, 260, 201, 31))
        self.newFolderPathInput.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.newFolderPathInput.setObjectName("newFolderPathInput")
        self.chooseNewFolderButton = QtWidgets.QPushButton(exportData)
        self.chooseNewFolderButton.setGeometry(QtCore.QRect(610, 300, 131, 41))
        self.chooseNewFolderButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.chooseNewFolderButton.setObjectName("chooseNewFolderButton")
        self.newFolderPathLabel = QtWidgets.QLabel(exportData)
        self.newFolderPathLabel.setGeometry(QtCore.QRect(610, 200, 271, 51))
        self.newFolderPathLabel.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.newFolderPathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newFolderPathLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.newFolderPathLabel.setObjectName("newFolderPathLabel")
        self.clearNewFolderButton = QtWidgets.QPushButton(exportData)
        self.clearNewFolderButton.setGeometry(QtCore.QRect(750, 300, 131, 41))
        self.clearNewFolderButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clearNewFolderButton.setObjectName("clearNewFolderButton")
        self.newFileNameInput = QtWidgets.QLineEdit(exportData)
        self.newFileNameInput.setGeometry(QtCore.QRect(650, 440, 201, 31))
        self.newFileNameInput.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.newFileNameInput.setAlignment(QtCore.Qt.AlignCenter)
        self.newFileNameInput.setObjectName("newFileNameInput")
        self.createNewFileButton = QtWidgets.QPushButton(exportData)
        self.createNewFileButton.setGeometry(QtCore.QRect(640, 590, 221, 41))
        self.createNewFileButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.createNewFileButton.setObjectName("createNewFileButton")
        self.newFileNameLabel = QtWidgets.QLabel(exportData)
        self.newFileNameLabel.setGeometry(QtCore.QRect(610, 380, 271, 51))
        self.newFileNameLabel.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.newFileNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newFileNameLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.newFileNameLabel.setObjectName("newFileNameLabel")
        self.appendFileButton = QtWidgets.QPushButton(exportData)
        self.appendFileButton.setGeometry(QtCore.QRect(640, 520, 221, 41))
        self.appendFileButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.appendFileButton.setObjectName("appendFileButton")
        self.appendFileBackButton = QtWidgets.QPushButton(exportData)
        self.appendFileBackButton.setGeometry(QtCore.QRect(640, 590, 221, 41))
        self.appendFileBackButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.appendFileBackButton.setObjectName("appendFileBackButton")
        self.newFileBackButton = QtWidgets.QPushButton(exportData)
        self.newFileBackButton.setGeometry(QtCore.QRect(640, 650, 221, 41))
        self.newFileBackButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.newFileBackButton.setObjectName("newFileBackButton")
        self.fileNameErrorLabel = QtWidgets.QLabel(exportData)
        self.fileNameErrorLabel.setGeometry(QtCore.QRect(540, 480, 421, 81))
        self.fileNameErrorLabel.setStyleSheet("QLabel {\n"
"    color: rgb(255, 0, 23);\n"
"    font-size: 20px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.fileNameErrorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fileNameErrorLabel.setObjectName("fileNameErrorLabel")
        self.fileNameWarningLabel = QtWidgets.QLabel(exportData)
        self.fileNameWarningLabel.setGeometry(QtCore.QRect(540, 490, 421, 81))
        self.fileNameWarningLabel.setStyleSheet("QLabel {\n"
"    color: rgb(255, 0, 23);\n"
"    font-size: 20px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.fileNameWarningLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fileNameWarningLabel.setObjectName("fileNameWarningLabel")
        self.dataSavedSuccessfullyLabel = QtWidgets.QLabel(exportData)
        self.dataSavedSuccessfullyLabel.setGeometry(QtCore.QRect(540, 300, 421, 81))
        self.dataSavedSuccessfullyLabel.setStyleSheet("QLabel {\n"
"    color: rgb(23, 255, 0);\n"
"    font-size: 30px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.dataSavedSuccessfullyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dataSavedSuccessfullyLabel.setObjectName("dataSavedSuccessfullyLabel")

        self.retranslateUi(exportData)
        QtCore.QMetaObject.connectSlotsByName(exportData)

    def retranslateUi(self, exportData):
        _translate = QtCore.QCoreApplication.translate
        exportData.setWindowTitle(_translate("exportData", "Export Data"))
        self.widget.setToolTip(_translate("exportData", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("exportData", "Image Selection:"))
        self.label_2.setText(_translate("exportData", "Image:"))
        self.imagePathInput.setText(_translate("exportData", "Sample filename "))
        self.label_4.setText(_translate("exportData", "Region of Interest (ROI) Selection"))
        self.label_7.setText(_translate("exportData", "Radio Frequency Data Analysis"))
        self.label_8.setText(_translate("exportData", "Export Results"))
        self.label_6.setText(_translate("exportData", "Analysis Parameter Selection"))
        self.backButton.setText(_translate("exportData", "Back"))
        self.selectDataLabel.setText(_translate("exportData", "Select Data Export Method:"))
        self.appendFileOptionButton.setToolTip(_translate("exportData", "<html><head/><body><p><br/></p></body></html>"))
        self.appendFileOptionButton.setText(_translate("exportData", "Append Data onto Existing Excel File"))
        self.clearAppendFileButton.setText(_translate("exportData", "Clear Path"))
        self.appendFileLabel.setText(_translate("exportData", "Excel File to Append to:"))
        self.chooseAppendFileButton.setText(_translate("exportData", "Choose File"))
        self.newFileOptionButton.setToolTip(_translate("exportData", "<html><head/><body><p><br/></p></body></html>"))
        self.newFileOptionButton.setText(_translate("exportData", "Save to New Excel File"))
        self.chooseNewFolderButton.setText(_translate("exportData", "Choose Folder"))
        self.newFolderPathLabel.setText(_translate("exportData", "Folder to save new file in:"))
        self.clearNewFolderButton.setText(_translate("exportData", "Clear Path"))
        self.createNewFileButton.setText(_translate("exportData", "Create File"))
        self.newFileNameLabel.setText(_translate("exportData", "Type name of new file:\n"
"(no spaces,  must end in \".xlsx\")"))
        self.appendFileButton.setText(_translate("exportData", "Append Data to File"))
        self.appendFileBackButton.setText(_translate("exportData", "Back"))
        self.newFileBackButton.setText(_translate("exportData", "Back"))
        self.fileNameErrorLabel.setText(_translate("exportData", "ERROR: Filename must not contain a space\n"
"and must end in \".xlsx\""))
        self.fileNameWarningLabel.setText(_translate("exportData", "WARNING: If file of specified folder and filename\n"
"already exists,  that file will be\n"
"deleted and overwritten"))
        self.dataSavedSuccessfullyLabel.setText(_translate("exportData", "Data saved successfully!"))
