# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CeusTool3d/ticAnalysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ticEditor(object):
    def setupUi(self, ticEditor):
        ticEditor.setObjectName("ticEditor")
        ticEditor.resize(1175, 749)
        ticEditor.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.analysisParamsLabel_2 = QtWidgets.QLabel(ticEditor)
        self.analysisParamsLabel_2.setGeometry(QtCore.QRect(470, -20, 571, 131))
        self.analysisParamsLabel_2.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.analysisParamsLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.analysisParamsLabel_2.setScaledContents(False)
        self.analysisParamsLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.analysisParamsLabel_2.setWordWrap(True)
        self.analysisParamsLabel_2.setObjectName("analysisParamsLabel_2")
        self.selectT0Button = QtWidgets.QPushButton(ticEditor)
        self.selectT0Button.setGeometry(QtCore.QRect(680, 690, 171, 41))
        self.selectT0Button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.selectT0Button.setObjectName("selectT0Button")
        self.sidebar = QtWidgets.QWidget(ticEditor)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 341, 751))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.imageSelectionSidebar = QtWidgets.QFrame(self.sidebar)
        self.imageSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.imageSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.imageSelectionSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageSelectionSidebar.setObjectName("imageSelectionSidebar")
        self.imageSelectionLabelSidebar = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imageSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.imageSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignCenter)
        self.imageSelectionLabelSidebar.setObjectName("imageSelectionLabelSidebar")
        self.imageLabel = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imageLabel.setGeometry(QtCore.QRect(-60, 50, 191, 51))
        self.imageLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.imagePathInput = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imagePathInput.setGeometry(QtCore.QRect(100, 50, 241, 51))
        self.imagePathInput.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.imagePathInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.imagePathInput.setObjectName("imagePathInput")
        self.roiSidebar = QtWidgets.QFrame(self.sidebar)
        self.roiSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.roiSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.roiSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.roiSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.roiSidebar.setObjectName("roiSidebar")
        self.roiSidebarLabel = QtWidgets.QLabel(self.roiSidebar)
        self.roiSidebarLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.roiSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.roiSidebarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.roiSidebarLabel.setObjectName("roiSidebarLabel")
        self.rfAnalysisSidebar = QtWidgets.QFrame(self.sidebar)
        self.rfAnalysisSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.rfAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.rfAnalysisSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rfAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rfAnalysisSidebar.setObjectName("rfAnalysisSidebar")
        self.rfAnalysisLabel = QtWidgets.QLabel(self.rfAnalysisSidebar)
        self.rfAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.rfAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.rfAnalysisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rfAnalysisLabel.setObjectName("rfAnalysisLabel")
        self.ticAnalysisSidebar = QtWidgets.QFrame(self.sidebar)
        self.ticAnalysisSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.ticAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.ticAnalysisSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ticAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ticAnalysisSidebar.setObjectName("ticAnalysisSidebar")
        self.ticAnalysisLabel = QtWidgets.QLabel(self.ticAnalysisSidebar)
        self.ticAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.ticAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.ticAnalysisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ticAnalysisLabel.setObjectName("ticAnalysisLabel")
        self.analysisParamsSidebar = QtWidgets.QFrame(ticEditor)
        self.analysisParamsSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisParamsSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisParamsSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.analysisParamsSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.analysisParamsSidebar.setObjectName("analysisParamsSidebar")
        self.analysisParamsLabel = QtWidgets.QLabel(self.analysisParamsSidebar)
        self.analysisParamsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisParamsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisParamsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.analysisParamsLabel.setObjectName("analysisParamsLabel")
        self.ticFrame = QtWidgets.QFrame(ticEditor)
        self.ticFrame.setGeometry(QtCore.QRect(400, 360, 721, 311))
        self.ticFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ticFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ticFrame.setObjectName("ticFrame")
        self.t0Slider = QtWidgets.QSlider(ticEditor)
        self.t0Slider.setGeometry(QtCore.QRect(490, 690, 281, 41))
        self.t0Slider.setOrientation(QtCore.Qt.Horizontal)
        self.t0Slider.setObjectName("t0Slider")
        self.acceptT0Button = QtWidgets.QPushButton(ticEditor)
        self.acceptT0Button.setGeometry(QtCore.QRect(870, 690, 171, 41))
        self.acceptT0Button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.acceptT0Button.setObjectName("acceptT0Button")
        self.deSelectLastPointButton = QtWidgets.QPushButton(ticEditor)
        self.deSelectLastPointButton.setGeometry(QtCore.QRect(350, 690, 181, 41))
        self.deSelectLastPointButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.deSelectLastPointButton.setObjectName("deSelectLastPointButton")
        self.removeSelectedPointsButton = QtWidgets.QPushButton(ticEditor)
        self.removeSelectedPointsButton.setGeometry(QtCore.QRect(560, 690, 181, 41))
        self.removeSelectedPointsButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.removeSelectedPointsButton.setObjectName("removeSelectedPointsButton")
        self.restoreLastPointsButton = QtWidgets.QPushButton(ticEditor)
        self.restoreLastPointsButton.setGeometry(QtCore.QRect(770, 690, 181, 41))
        self.restoreLastPointsButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.restoreLastPointsButton.setObjectName("restoreLastPointsButton")
        self.acceptTicButton = QtWidgets.QPushButton(ticEditor)
        self.acceptTicButton.setGeometry(QtCore.QRect(980, 690, 181, 41))
        self.acceptTicButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.acceptTicButton.setObjectName("acceptTicButton")
        self.backButton = QtWidgets.QPushButton(ticEditor)
        self.backButton.setGeometry(QtCore.QRect(10, 690, 131, 41))
        self.backButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.backButton.setObjectName("backButton")
        self.maskLayerAx = QtWidgets.QLabel(ticEditor)
        self.maskLayerAx.setGeometry(QtCore.QRect(360, 120, 231, 211))
        self.maskLayerAx.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.maskLayerAx.setText("")
        self.maskLayerAx.setObjectName("maskLayerAx")
        self.axCoverLabel = QtWidgets.QLabel(ticEditor)
        self.axCoverLabel.setGeometry(QtCore.QRect(360, 120, 231, 211))
        self.axCoverLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.axCoverLabel.setText("")
        self.axCoverLabel.setObjectName("axCoverLabel")
        self.axialPlaneLabel = QtWidgets.QLabel(ticEditor)
        self.axialPlaneLabel.setGeometry(QtCore.QRect(340, 80, 271, 51))
        self.axialPlaneLabel.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.axialPlaneLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.axialPlaneLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.axialPlaneLabel.setObjectName("axialPlaneLabel")
        self.axialPlane = QtWidgets.QLabel(ticEditor)
        self.axialPlane.setGeometry(QtCore.QRect(360, 120, 231, 211))
        self.axialPlane.setText("")
        self.axialPlane.setObjectName("axialPlane")
        self.sagCoverLabel = QtWidgets.QLabel(ticEditor)
        self.sagCoverLabel.setGeometry(QtCore.QRect(640, 120, 231, 211))
        self.sagCoverLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.sagCoverLabel.setText("")
        self.sagCoverLabel.setObjectName("sagCoverLabel")
        self.maskLayerSag = QtWidgets.QLabel(ticEditor)
        self.maskLayerSag.setGeometry(QtCore.QRect(640, 120, 231, 211))
        self.maskLayerSag.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.maskLayerSag.setText("")
        self.maskLayerSag.setObjectName("maskLayerSag")
        self.sagittalPlaneLabel = QtWidgets.QLabel(ticEditor)
        self.sagittalPlaneLabel.setGeometry(QtCore.QRect(620, 80, 271, 51))
        self.sagittalPlaneLabel.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.sagittalPlaneLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sagittalPlaneLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.sagittalPlaneLabel.setObjectName("sagittalPlaneLabel")
        self.sagPlane = QtWidgets.QLabel(ticEditor)
        self.sagPlane.setGeometry(QtCore.QRect(640, 120, 231, 211))
        self.sagPlane.setText("")
        self.sagPlane.setObjectName("sagPlane")
        self.corPlane = QtWidgets.QLabel(ticEditor)
        self.corPlane.setGeometry(QtCore.QRect(920, 120, 231, 211))
        self.corPlane.setText("")
        self.corPlane.setObjectName("corPlane")
        self.maskLayerCor = QtWidgets.QLabel(ticEditor)
        self.maskLayerCor.setGeometry(QtCore.QRect(920, 120, 231, 211))
        self.maskLayerCor.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.maskLayerCor.setText("")
        self.maskLayerCor.setObjectName("maskLayerCor")
        self.corCoverLabel = QtWidgets.QLabel(ticEditor)
        self.corCoverLabel.setGeometry(QtCore.QRect(920, 120, 231, 211))
        self.corCoverLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.corCoverLabel.setText("")
        self.corCoverLabel.setObjectName("corCoverLabel")
        self.coronalPlaneLabel = QtWidgets.QLabel(ticEditor)
        self.coronalPlaneLabel.setGeometry(QtCore.QRect(900, 80, 271, 51))
        self.coronalPlaneLabel.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.coronalPlaneLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.coronalPlaneLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.coronalPlaneLabel.setObjectName("coronalPlaneLabel")
        self.axialPlane.raise_()
        self.sagPlane.raise_()
        self.maskLayerSag.raise_()
        self.analysisParamsLabel_2.raise_()
        self.selectT0Button.raise_()
        self.sidebar.raise_()
        self.analysisParamsSidebar.raise_()
        self.ticFrame.raise_()
        self.t0Slider.raise_()
        self.acceptT0Button.raise_()
        self.deSelectLastPointButton.raise_()
        self.removeSelectedPointsButton.raise_()
        self.restoreLastPointsButton.raise_()
        self.acceptTicButton.raise_()
        self.backButton.raise_()
        self.maskLayerAx.raise_()
        self.axCoverLabel.raise_()
        self.axialPlaneLabel.raise_()
        self.sagCoverLabel.raise_()
        self.sagittalPlaneLabel.raise_()
        self.corPlane.raise_()
        self.maskLayerCor.raise_()
        self.corCoverLabel.raise_()
        self.coronalPlaneLabel.raise_()

        self.retranslateUi(ticEditor)
        QtCore.QMetaObject.connectSlotsByName(ticEditor)

    def retranslateUi(self, ticEditor):
        _translate = QtCore.QCoreApplication.translate
        ticEditor.setWindowTitle(_translate("ticEditor", "TIC Editor"))
        self.analysisParamsLabel_2.setText(_translate("ticEditor", "Time Intensity Curve (TIC) Editor:"))
        self.selectT0Button.setText(_translate("ticEditor", "Select Start Time (T0)"))
        self.sidebar.setToolTip(_translate("ticEditor", "<html><head/><body><p><br/></p></body></html>"))
        self.imageSelectionLabelSidebar.setText(_translate("ticEditor", "Image Selection:"))
        self.imageLabel.setText(_translate("ticEditor", "Image:"))
        self.imagePathInput.setText(_translate("ticEditor", "Sample filename "))
        self.roiSidebarLabel.setText(_translate("ticEditor", "Volume of Interest (VOI) Selection"))
        self.rfAnalysisLabel.setText(_translate("ticEditor", "Export Results"))
        self.ticAnalysisLabel.setText(_translate("ticEditor", "Contrast-Enhanced Ultrasound\n"
"(CEUS) Analysis"))
        self.analysisParamsLabel.setText(_translate("ticEditor", "TIC Modification"))
        self.acceptT0Button.setText(_translate("ticEditor", "Accept T0"))
        self.deSelectLastPointButton.setText(_translate("ticEditor", "De-Select Last Point"))
        self.removeSelectedPointsButton.setText(_translate("ticEditor", "Remove Selected Points"))
        self.restoreLastPointsButton.setText(_translate("ticEditor", "Restore Last Points"))
        self.acceptTicButton.setText(_translate("ticEditor", "Accept TIC"))
        self.backButton.setText(_translate("ticEditor", "Back"))
        self.axialPlaneLabel.setText(_translate("ticEditor", "Axial Plane"))
        self.sagittalPlaneLabel.setText(_translate("ticEditor", "Sagittal Plane"))
        self.coronalPlaneLabel.setText(_translate("ticEditor", "Coronal Plane"))
