# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CeusTool3d/voiSelection.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_constructVoi(object):
    def setupUi(self, constructVoi):
        constructVoi.setObjectName("constructVoi")
        constructVoi.resize(1175, 749)
        constructVoi.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.constructVoiLabel = QtWidgets.QLabel(constructVoi)
        self.constructVoiLabel.setGeometry(QtCore.QRect(390, 570, 361, 51))
        self.constructVoiLabel.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.constructVoiLabel.setTextFormat(QtCore.Qt.AutoText)
        self.constructVoiLabel.setScaledContents(False)
        self.constructVoiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.constructVoiLabel.setWordWrap(True)
        self.constructVoiLabel.setObjectName("constructVoiLabel")
        self.drawRoiButton = QtWidgets.QPushButton(constructVoi)
        self.drawRoiButton.setGeometry(QtCore.QRect(390, 630, 171, 41))
        self.drawRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 16px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.drawRoiButton.setCheckable(True)
        self.drawRoiButton.setChecked(False)
        self.drawRoiButton.setObjectName("drawRoiButton")
        self.undoLastPtButton = QtWidgets.QPushButton(constructVoi)
        self.undoLastPtButton.setGeometry(QtCore.QRect(580, 630, 171, 41))
        self.undoLastPtButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.undoLastPtButton.setCheckable(False)
        self.undoLastPtButton.setObjectName("undoLastPtButton")
        self.interpolateVoiButton = QtWidgets.QPushButton(constructVoi)
        self.interpolateVoiButton.setGeometry(QtCore.QRect(580, 690, 171, 41))
        self.interpolateVoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.interpolateVoiButton.setCheckable(False)
        self.interpolateVoiButton.setObjectName("interpolateVoiButton")
        self.closeRoiButton = QtWidgets.QPushButton(constructVoi)
        self.closeRoiButton.setGeometry(QtCore.QRect(390, 690, 171, 41))
        self.closeRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.closeRoiButton.setCheckable(False)
        self.closeRoiButton.setObjectName("closeRoiButton")
        self.redrawRoiButton = QtWidgets.QPushButton(constructVoi)
        self.redrawRoiButton.setGeometry(QtCore.QRect(390, 690, 171, 41))
        self.redrawRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.redrawRoiButton.setCheckable(False)
        self.redrawRoiButton.setObjectName("redrawRoiButton")
        self.axialPlaneLabel = QtWidgets.QLabel(constructVoi)
        self.axialPlaneLabel.setGeometry(QtCore.QRect(420, 0, 271, 51))
        self.axialPlaneLabel.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.axialPlaneLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.axialPlaneLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.axialPlaneLabel.setObjectName("axialPlaneLabel")
        self.sagittalPlaneLabel = QtWidgets.QLabel(constructVoi)
        self.sagittalPlaneLabel.setGeometry(QtCore.QRect(840, 0, 271, 51))
        self.sagittalPlaneLabel.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.sagittalPlaneLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sagittalPlaneLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.sagittalPlaneLabel.setObjectName("sagittalPlaneLabel")
        self.coronalPlaneLabel = QtWidgets.QLabel(constructVoi)
        self.coronalPlaneLabel.setGeometry(QtCore.QRect(840, 370, 271, 51))
        self.coronalPlaneLabel.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.coronalPlaneLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.coronalPlaneLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.coronalPlaneLabel.setObjectName("coronalPlaneLabel")
        self.axialFrameNum = QtWidgets.QLabel(constructVoi)
        self.axialFrameNum.setGeometry(QtCore.QRect(640, 350, 41, 31))
        self.axialFrameNum.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.axialFrameNum.setAlignment(QtCore.Qt.AlignCenter)
        self.axialFrameNum.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.axialFrameNum.setObjectName("axialFrameNum")
        self.axialTotalFrames = QtWidgets.QLabel(constructVoi)
        self.axialTotalFrames.setGeometry(QtCore.QRect(700, 350, 61, 31))
        self.axialTotalFrames.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.axialTotalFrames.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.axialTotalFrames.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.axialTotalFrames.setObjectName("axialTotalFrames")
        self.axialOfLabel = QtWidgets.QLabel(constructVoi)
        self.axialOfLabel.setGeometry(QtCore.QRect(665, 350, 41, 31))
        self.axialOfLabel.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.axialOfLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.axialOfLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.axialOfLabel.setObjectName("axialOfLabel")
        self.sagittalFrameNum = QtWidgets.QLabel(constructVoi)
        self.sagittalFrameNum.setGeometry(QtCore.QRect(1050, 350, 41, 31))
        self.sagittalFrameNum.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.sagittalFrameNum.setAlignment(QtCore.Qt.AlignCenter)
        self.sagittalFrameNum.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.sagittalFrameNum.setObjectName("sagittalFrameNum")
        self.sagittalOfLabel = QtWidgets.QLabel(constructVoi)
        self.sagittalOfLabel.setGeometry(QtCore.QRect(1075, 350, 41, 31))
        self.sagittalOfLabel.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.sagittalOfLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sagittalOfLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.sagittalOfLabel.setObjectName("sagittalOfLabel")
        self.sagittalTotalFrames = QtWidgets.QLabel(constructVoi)
        self.sagittalTotalFrames.setGeometry(QtCore.QRect(1110, 350, 61, 31))
        self.sagittalTotalFrames.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.sagittalTotalFrames.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sagittalTotalFrames.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.sagittalTotalFrames.setObjectName("sagittalTotalFrames")
        self.coronalFrameNum = QtWidgets.QLabel(constructVoi)
        self.coronalFrameNum.setGeometry(QtCore.QRect(1050, 710, 41, 31))
        self.coronalFrameNum.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.coronalFrameNum.setAlignment(QtCore.Qt.AlignCenter)
        self.coronalFrameNum.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.coronalFrameNum.setObjectName("coronalFrameNum")
        self.coronalOfLabel = QtWidgets.QLabel(constructVoi)
        self.coronalOfLabel.setGeometry(QtCore.QRect(1075, 710, 41, 31))
        self.coronalOfLabel.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.coronalOfLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.coronalOfLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.coronalOfLabel.setObjectName("coronalOfLabel")
        self.coronalTotalFrames = QtWidgets.QLabel(constructVoi)
        self.coronalTotalFrames.setGeometry(QtCore.QRect(1110, 710, 61, 31))
        self.coronalTotalFrames.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.coronalTotalFrames.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.coronalTotalFrames.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.coronalTotalFrames.setObjectName("coronalTotalFrames")
        self.curSliceLabel = QtWidgets.QLabel(constructVoi)
        self.curSliceLabel.setGeometry(QtCore.QRect(380, 370, 361, 51))
        self.curSliceLabel.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.curSliceLabel.setTextFormat(QtCore.Qt.AutoText)
        self.curSliceLabel.setScaledContents(False)
        self.curSliceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.curSliceLabel.setWordWrap(True)
        self.curSliceLabel.setObjectName("curSliceLabel")
        self.curSliceSlider = QtWidgets.QSlider(constructVoi)
        self.curSliceSlider.setGeometry(QtCore.QRect(399, 420, 191, 41))
        self.curSliceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.curSliceSlider.setObjectName("curSliceSlider")
        self.curSliceOfLabel = QtWidgets.QLabel(constructVoi)
        self.curSliceOfLabel.setGeometry(QtCore.QRect(695, 425, 41, 31))
        self.curSliceOfLabel.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.curSliceOfLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.curSliceOfLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.curSliceOfLabel.setObjectName("curSliceOfLabel")
        self.curSliceTotal = QtWidgets.QLabel(constructVoi)
        self.curSliceTotal.setGeometry(QtCore.QRect(730, 425, 61, 31))
        self.curSliceTotal.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.curSliceTotal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.curSliceTotal.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.curSliceTotal.setObjectName("curSliceTotal")
        self.voiAlphaLabel = QtWidgets.QLabel(constructVoi)
        self.voiAlphaLabel.setGeometry(QtCore.QRect(380, 475, 361, 51))
        self.voiAlphaLabel.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.voiAlphaLabel.setTextFormat(QtCore.Qt.AutoText)
        self.voiAlphaLabel.setScaledContents(False)
        self.voiAlphaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.voiAlphaLabel.setWordWrap(True)
        self.voiAlphaLabel.setObjectName("voiAlphaLabel")
        self.voiAlphaSpinBox = QtWidgets.QSpinBox(constructVoi)
        self.voiAlphaSpinBox.setGeometry(QtCore.QRect(640, 525, 48, 24))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.voiAlphaSpinBox.setFont(font)
        self.voiAlphaSpinBox.setStyleSheet("QSpinBox{\n"
"    background-color: white,\n"
"}")
        self.voiAlphaSpinBox.setObjectName("voiAlphaSpinBox")
        self.voiAlphaTotal = QtWidgets.QLabel(constructVoi)
        self.voiAlphaTotal.setGeometry(QtCore.QRect(730, 520, 61, 31))
        self.voiAlphaTotal.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.voiAlphaTotal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.voiAlphaTotal.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.voiAlphaTotal.setObjectName("voiAlphaTotal")
        self.voiAlphaOfLabel = QtWidgets.QLabel(constructVoi)
        self.voiAlphaOfLabel.setGeometry(QtCore.QRect(695, 520, 41, 31))
        self.voiAlphaOfLabel.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.voiAlphaOfLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.voiAlphaOfLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.voiAlphaOfLabel.setObjectName("voiAlphaOfLabel")
        self.sidebar = QtWidgets.QWidget(constructVoi)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 341, 751))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.imageSelectionSidebar = QtWidgets.QFrame(self.sidebar)
        self.imageSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.imageSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.imageSelectionSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageSelectionSidebar.setObjectName("imageSelectionSidebar")
        self.imageSelectionLabelSidebar = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imageSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.imageSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignCenter)
        self.imageSelectionLabelSidebar.setObjectName("imageSelectionLabelSidebar")
        self.imageLabel = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imageLabel.setGeometry(QtCore.QRect(-60, 50, 191, 51))
        self.imageLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.imagePathInput = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imagePathInput.setGeometry(QtCore.QRect(100, 50, 241, 51))
        self.imagePathInput.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.imagePathInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.imagePathInput.setObjectName("imagePathInput")
        self.roiSidebar = QtWidgets.QFrame(self.sidebar)
        self.roiSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.roiSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.roiSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.roiSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.roiSidebar.setObjectName("roiSidebar")
        self.roiSidebarLabel = QtWidgets.QLabel(self.roiSidebar)
        self.roiSidebarLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.roiSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.roiSidebarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.roiSidebarLabel.setObjectName("roiSidebarLabel")
        self.rfAnalysisSidebar = QtWidgets.QFrame(self.sidebar)
        self.rfAnalysisSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.rfAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.rfAnalysisSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rfAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rfAnalysisSidebar.setObjectName("rfAnalysisSidebar")
        self.rfAnalysisLabel = QtWidgets.QLabel(self.rfAnalysisSidebar)
        self.rfAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.rfAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.rfAnalysisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rfAnalysisLabel.setObjectName("rfAnalysisLabel")
        self.ticAnalysisSidebar = QtWidgets.QFrame(self.sidebar)
        self.ticAnalysisSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.ticAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.ticAnalysisSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ticAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ticAnalysisSidebar.setObjectName("ticAnalysisSidebar")
        self.ticAnalysisLabel = QtWidgets.QLabel(self.ticAnalysisSidebar)
        self.ticAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.ticAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.ticAnalysisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ticAnalysisLabel.setObjectName("ticAnalysisLabel")
        self.saveDataButton = QtWidgets.QPushButton(self.sidebar)
        self.saveDataButton.setGeometry(QtCore.QRect(150, 640, 181, 41))
        self.saveDataButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.saveDataButton.setObjectName("saveDataButton")
        self.analysisParamsSidebar = QtWidgets.QFrame(constructVoi)
        self.analysisParamsSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisParamsSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisParamsSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.analysisParamsSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.analysisParamsSidebar.setObjectName("analysisParamsSidebar")
        self.analysisParamsLabel = QtWidgets.QLabel(self.analysisParamsSidebar)
        self.analysisParamsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisParamsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisParamsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.analysisParamsLabel.setObjectName("analysisParamsLabel")
        self.axialPlane = QtWidgets.QLabel(constructVoi)
        self.axialPlane.setGeometry(QtCore.QRect(400, 40, 321, 301))
        self.axialPlane.setText("")
        self.axialPlane.setObjectName("axialPlane")
        self.maskLayerAx = QtWidgets.QLabel(constructVoi)
        self.maskLayerAx.setGeometry(QtCore.QRect(400, 40, 321, 301))
        self.maskLayerAx.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.maskLayerAx.setText("")
        self.maskLayerAx.setObjectName("maskLayerAx")
        self.sagPlane = QtWidgets.QLabel(constructVoi)
        self.sagPlane.setGeometry(QtCore.QRect(810, 40, 321, 301))
        self.sagPlane.setText("")
        self.sagPlane.setObjectName("sagPlane")
        self.corPlane = QtWidgets.QLabel(constructVoi)
        self.corPlane.setGeometry(QtCore.QRect(810, 410, 321, 301))
        self.corPlane.setText("")
        self.corPlane.setObjectName("corPlane")
        self.axCoverLabel = QtWidgets.QLabel(constructVoi)
        self.axCoverLabel.setGeometry(QtCore.QRect(400, 40, 321, 301))
        self.axCoverLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.axCoverLabel.setText("")
        self.axCoverLabel.setObjectName("axCoverLabel")
        self.maskLayerSag = QtWidgets.QLabel(constructVoi)
        self.maskLayerSag.setGeometry(QtCore.QRect(810, 40, 321, 301))
        self.maskLayerSag.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.maskLayerSag.setText("")
        self.maskLayerSag.setObjectName("maskLayerSag")
        self.maskLayerCor = QtWidgets.QLabel(constructVoi)
        self.maskLayerCor.setGeometry(QtCore.QRect(810, 410, 321, 301))
        self.maskLayerCor.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.maskLayerCor.setText("")
        self.maskLayerCor.setObjectName("maskLayerCor")
        self.sagCoverLabel = QtWidgets.QLabel(constructVoi)
        self.sagCoverLabel.setGeometry(QtCore.QRect(810, 40, 321, 301))
        self.sagCoverLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.sagCoverLabel.setText("")
        self.sagCoverLabel.setObjectName("sagCoverLabel")
        self.corCoverLabel = QtWidgets.QLabel(constructVoi)
        self.corCoverLabel.setGeometry(QtCore.QRect(810, 410, 321, 301))
        self.corCoverLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.corCoverLabel.setText("")
        self.corCoverLabel.setObjectName("corCoverLabel")
        self.voiAlphaStatus = QtWidgets.QProgressBar(constructVoi)
        self.voiAlphaStatus.setGeometry(QtCore.QRect(399, 520, 191, 41))
        self.voiAlphaStatus.setProperty("value", 24)
        self.voiAlphaStatus.setObjectName("voiAlphaStatus")
        self.continueButton = QtWidgets.QPushButton(constructVoi)
        self.continueButton.setGeometry(QtCore.QRect(580, 650, 171, 41))
        self.continueButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.continueButton.setCheckable(False)
        self.continueButton.setObjectName("continueButton")
        self.aucVal = QtWidgets.QLabel(constructVoi)
        self.aucVal.setGeometry(QtCore.QRect(740, 570, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.aucVal.setFont(font)
        self.aucVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.aucVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.aucVal.setObjectName("aucVal")
        self.aucLabel = QtWidgets.QLabel(constructVoi)
        self.aucLabel.setGeometry(QtCore.QRect(680, 570, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.aucLabel.setFont(font)
        self.aucLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.aucLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.aucLabel.setObjectName("aucLabel")
        self.tpVal = QtWidgets.QLabel(constructVoi)
        self.tpVal.setGeometry(QtCore.QRect(740, 630, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tpVal.setFont(font)
        self.tpVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.tpVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tpVal.setObjectName("tpVal")
        self.tmppvVal = QtWidgets.QLabel(constructVoi)
        self.tmppvVal.setGeometry(QtCore.QRect(740, 650, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tmppvVal.setFont(font)
        self.tmppvVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.tmppvVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tmppvVal.setObjectName("tmppvVal")
        self.mttLabel = QtWidgets.QLabel(constructVoi)
        self.mttLabel.setGeometry(QtCore.QRect(680, 610, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mttLabel.setFont(font)
        self.mttLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.mttLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mttLabel.setObjectName("mttLabel")
        self.peLabel = QtWidgets.QLabel(constructVoi)
        self.peLabel.setGeometry(QtCore.QRect(680, 590, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.peLabel.setFont(font)
        self.peLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.peLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.peLabel.setObjectName("peLabel")
        self.voiVolumeLabel = QtWidgets.QLabel(constructVoi)
        self.voiVolumeLabel.setGeometry(QtCore.QRect(680, 700, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.voiVolumeLabel.setFont(font)
        self.voiVolumeLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.voiVolumeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.voiVolumeLabel.setObjectName("voiVolumeLabel")
        self.voiVolumeVal = QtWidgets.QLabel(constructVoi)
        self.voiVolumeVal.setGeometry(QtCore.QRect(790, 700, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.voiVolumeVal.setFont(font)
        self.voiVolumeVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.voiVolumeVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.voiVolumeVal.setObjectName("voiVolumeVal")
        self.mttVal = QtWidgets.QLabel(constructVoi)
        self.mttVal.setGeometry(QtCore.QRect(740, 610, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mttVal.setFont(font)
        self.mttVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.mttVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mttVal.setObjectName("mttVal")
        self.ticDisplay = QtWidgets.QFrame(constructVoi)
        self.ticDisplay.setGeometry(QtCore.QRect(350, 590, 321, 121))
        self.ticDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ticDisplay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ticDisplay.setObjectName("ticDisplay")
        self.resultsLabel = QtWidgets.QLabel(constructVoi)
        self.resultsLabel.setGeometry(QtCore.QRect(390, 540, 361, 51))
        self.resultsLabel.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.resultsLabel.setTextFormat(QtCore.Qt.AutoText)
        self.resultsLabel.setScaledContents(False)
        self.resultsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultsLabel.setWordWrap(True)
        self.resultsLabel.setObjectName("resultsLabel")
        self.peVal = QtWidgets.QLabel(constructVoi)
        self.peVal.setGeometry(QtCore.QRect(740, 590, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.peVal.setFont(font)
        self.peVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.peVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.peVal.setObjectName("peVal")
        self.tpLabel = QtWidgets.QLabel(constructVoi)
        self.tpLabel.setGeometry(QtCore.QRect(680, 630, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tpLabel.setFont(font)
        self.tpLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.tpLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tpLabel.setObjectName("tpLabel")
        self.tmppvLabel = QtWidgets.QLabel(constructVoi)
        self.tmppvLabel.setGeometry(QtCore.QRect(680, 650, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tmppvLabel.setFont(font)
        self.tmppvLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.tmppvLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tmppvLabel.setObjectName("tmppvLabel")
        self.backButton = QtWidgets.QPushButton(constructVoi)
        self.backButton.setGeometry(QtCore.QRect(10, 690, 131, 41))
        self.backButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.backButton.setObjectName("backButton")
        self.restartVoiButton = QtWidgets.QPushButton(constructVoi)
        self.restartVoiButton.setGeometry(QtCore.QRect(390, 650, 171, 41))
        self.restartVoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.restartVoiButton.setCheckable(False)
        self.restartVoiButton.setObjectName("restartVoiButton")
        self.curSliceSpinBox = QtWidgets.QDoubleSpinBox(constructVoi)
        self.curSliceSpinBox.setGeometry(QtCore.QRect(630, 430, 68, 24))
        self.curSliceSpinBox.setStyleSheet("QDoubleSpinBox {\n"
"    background: white;\n"
"}")
        self.curSliceSpinBox.setObjectName("curSliceSpinBox")
        self.voiAdviceLabel = QtWidgets.QLabel(constructVoi)
        self.voiAdviceLabel.setGeometry(QtCore.QRect(380, 500, 361, 51))
        self.voiAdviceLabel.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.voiAdviceLabel.setTextFormat(QtCore.Qt.AutoText)
        self.voiAdviceLabel.setScaledContents(False)
        self.voiAdviceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.voiAdviceLabel.setWordWrap(True)
        self.voiAdviceLabel.setObjectName("voiAdviceLabel")
        self.exportDataButton = QtWidgets.QPushButton(constructVoi)
        self.exportDataButton.setGeometry(QtCore.QRect(150, 690, 181, 41))
        self.exportDataButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.exportDataButton.setObjectName("exportDataButton")

        self.retranslateUi(constructVoi)
        QtCore.QMetaObject.connectSlotsByName(constructVoi)

    def retranslateUi(self, constructVoi):
        _translate = QtCore.QCoreApplication.translate
        constructVoi.setWindowTitle(_translate("constructVoi", "Select Volume of Interest"))
        self.constructVoiLabel.setText(_translate("constructVoi", "Construct Volume of Interest (VOI):"))
        self.drawRoiButton.setText(_translate("constructVoi", "Draw ROI"))
        self.undoLastPtButton.setText(_translate("constructVoi", "Undo Last Point"))
        self.interpolateVoiButton.setText(_translate("constructVoi", "Interpolate VOI"))
        self.closeRoiButton.setText(_translate("constructVoi", "Close ROI"))
        self.redrawRoiButton.setText(_translate("constructVoi", "Undo Last ROI"))
        self.axialPlaneLabel.setText(_translate("constructVoi", "Axial Plane"))
        self.sagittalPlaneLabel.setText(_translate("constructVoi", "Sagittal Plane"))
        self.coronalPlaneLabel.setText(_translate("constructVoi", "Coronal Plane"))
        self.axialFrameNum.setText(_translate("constructVoi", "0"))
        self.axialTotalFrames.setText(_translate("constructVoi", "0"))
        self.axialOfLabel.setText(_translate("constructVoi", "of"))
        self.sagittalFrameNum.setText(_translate("constructVoi", "0"))
        self.sagittalOfLabel.setText(_translate("constructVoi", "of"))
        self.sagittalTotalFrames.setText(_translate("constructVoi", "0"))
        self.coronalFrameNum.setText(_translate("constructVoi", "0"))
        self.coronalOfLabel.setText(_translate("constructVoi", "of"))
        self.coronalTotalFrames.setText(_translate("constructVoi", "0"))
        self.curSliceLabel.setText(_translate("constructVoi", "Current Slice (in seconds):"))
        self.curSliceOfLabel.setText(_translate("constructVoi", "of"))
        self.curSliceTotal.setText(_translate("constructVoi", "0"))
        self.voiAlphaLabel.setText(_translate("constructVoi", "VOI Alpha:"))
        self.voiAlphaTotal.setText(_translate("constructVoi", "255"))
        self.voiAlphaOfLabel.setText(_translate("constructVoi", "of"))
        self.sidebar.setToolTip(_translate("constructVoi", "<html><head/><body><p><br/></p></body></html>"))
        self.imageSelectionLabelSidebar.setText(_translate("constructVoi", "Image Selection:"))
        self.imageLabel.setText(_translate("constructVoi", "Image:"))
        self.imagePathInput.setText(_translate("constructVoi", "Sample filename "))
        self.roiSidebarLabel.setText(_translate("constructVoi", "Volume of Interest (VOI) Selection"))
        self.rfAnalysisLabel.setText(_translate("constructVoi", "Export Results"))
        self.ticAnalysisLabel.setText(_translate("constructVoi", "Contrast-Enhanced Ultrasound\n"
"(CEUS) Analysis"))
        self.saveDataButton.setText(_translate("constructVoi", "Save Data"))
        self.analysisParamsLabel.setText(_translate("constructVoi", "TIC Modification"))
        self.continueButton.setText(_translate("constructVoi", "Continue"))
        self.aucVal.setText(_translate("constructVoi", "0"))
        self.aucLabel.setText(_translate("constructVoi", "AUC:"))
        self.tpVal.setText(_translate("constructVoi", "0"))
        self.tmppvVal.setText(_translate("constructVoi", "0"))
        self.mttLabel.setText(_translate("constructVoi", "MTT:"))
        self.peLabel.setText(_translate("constructVoi", "PE:"))
        self.voiVolumeLabel.setText(_translate("constructVoi", "VOI Vol (mm^3):"))
        self.voiVolumeVal.setText(_translate("constructVoi", "0"))
        self.mttVal.setText(_translate("constructVoi", "0"))
        self.resultsLabel.setText(_translate("constructVoi", "Results:"))
        self.peVal.setText(_translate("constructVoi", "0"))
        self.tpLabel.setText(_translate("constructVoi", "TP:"))
        self.tmppvLabel.setText(_translate("constructVoi", "TMPPV:"))
        self.backButton.setText(_translate("constructVoi", "Back"))
        self.restartVoiButton.setText(_translate("constructVoi", "Restart VOI"))
        self.voiAdviceLabel.setText(_translate("constructVoi", "For best results,  draw 1 ROI in each plane before interpolating"))
        self.exportDataButton.setText(_translate("constructVoi", "Export Data"))
