# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qusPage(object):
    def setupUi(self, qusPage):
        qusPage.setObjectName("qusPage")
        qusPage.resize(1175, 749)
        qusPage.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.qusLabel = QtWidgets.QLabel(qusPage)
        self.qusLabel.setGeometry(QtCore.QRect(350, 30, 491, 131))
        self.qusLabel.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.qusLabel.setTextFormat(QtCore.Qt.AutoText)
        self.qusLabel.setScaledContents(False)
        self.qusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.qusLabel.setWordWrap(True)
        self.qusLabel.setObjectName("qusLabel")
        self.utc2dButton = QtWidgets.QPushButton(qusPage)
        self.utc2dButton.setGeometry(QtCore.QRect(350, 220, 491, 51))
        self.utc2dButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.utc2dButton.setObjectName("utc2dButton")
        self.utc3dButton = QtWidgets.QPushButton(qusPage)
        self.utc3dButton.setGeometry(QtCore.QRect(350, 330, 491, 51))
        self.utc3dButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.utc3dButton.setObjectName("utc3dButton")
        self.ceus2dButton = QtWidgets.QPushButton(qusPage)
        self.ceus2dButton.setGeometry(QtCore.QRect(350, 440, 491, 51))
        self.ceus2dButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.ceus2dButton.setObjectName("ceus2dButton")
        self.ceus3dButton = QtWidgets.QPushButton(qusPage)
        self.ceus3dButton.setGeometry(QtCore.QRect(350, 550, 491, 51))
        self.ceus3dButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.ceus3dButton.setObjectName("ceus3dButton")

        self.retranslateUi(qusPage)
        QtCore.QMetaObject.connectSlotsByName(qusPage)

    def retranslateUi(self, qusPage):
        _translate = QtCore.QCoreApplication.translate
        qusPage.setWindowTitle(_translate("qusPage", "QUS Tools"))
        self.qusLabel.setText(_translate("qusPage", "Quantitative Ultrasound (QUS) Tools:"))
        self.utc2dButton.setToolTip(_translate("qusPage", "<html><head/><body><p><br/></p></body></html>"))
        self.utc2dButton.setText(_translate("qusPage", "2D Ultrasound Tissue Characterization (UTC) with RF Data"))
        self.utc3dButton.setToolTip(_translate("qusPage", "<html><head/><body><p><br/></p></body></html>"))
        self.utc3dButton.setText(_translate("qusPage", "2D Ultrasound Tissue Characterization (UTC) with IQ Data"))
        self.ceus2dButton.setToolTip(_translate("qusPage", "<html><head/><body><p><br/></p></body></html>"))
        self.ceus2dButton.setText(_translate("qusPage", "2D Contrast-Enhanced Ultrasound (CEUS) with Motion Correction"))
        self.ceus3dButton.setToolTip(_translate("qusPage", "<html><head/><body><p><br/></p></body></html>"))
        self.ceus3dButton.setText(_translate("qusPage", "3D Contrast-Enhanced Ultrasound (CEUS)"))
