# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CeusMcTool2d/ceusAnalysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ceusAnalysis(object):
    def setupUi(self, ceusAnalysis):
        ceusAnalysis.setObjectName("ceusAnalysis")
        ceusAnalysis.resize(1175, 749)
        ceusAnalysis.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.axialPlaneLabel = QtWidgets.QLabel(ceusAnalysis)
        self.axialPlaneLabel.setGeometry(QtCore.QRect(410, 100, 271, 51))
        self.axialPlaneLabel.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.axialPlaneLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.axialPlaneLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.axialPlaneLabel.setObjectName("axialPlaneLabel")
        self.sagittalPlaneLabel = QtWidgets.QLabel(ceusAnalysis)
        self.sagittalPlaneLabel.setGeometry(QtCore.QRect(830, 100, 271, 51))
        self.sagittalPlaneLabel.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.sagittalPlaneLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sagittalPlaneLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.sagittalPlaneLabel.setObjectName("sagittalPlaneLabel")
        self.curSliceLabel = QtWidgets.QLabel(ceusAnalysis)
        self.curSliceLabel.setGeometry(QtCore.QRect(300, 530, 361, 51))
        self.curSliceLabel.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.curSliceLabel.setTextFormat(QtCore.Qt.AutoText)
        self.curSliceLabel.setScaledContents(False)
        self.curSliceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.curSliceLabel.setWordWrap(True)
        self.curSliceLabel.setObjectName("curSliceLabel")
        self.curSliceSlider = QtWidgets.QSlider(ceusAnalysis)
        self.curSliceSlider.setGeometry(QtCore.QRect(380, 590, 191, 41))
        self.curSliceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.curSliceSlider.setObjectName("curSliceSlider")
        self.curSliceOfLabel = QtWidgets.QLabel(ceusAnalysis)
        self.curSliceOfLabel.setGeometry(QtCore.QRect(455, 650, 41, 31))
        self.curSliceOfLabel.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.curSliceOfLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.curSliceOfLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.curSliceOfLabel.setObjectName("curSliceOfLabel")
        self.sidebar = QtWidgets.QWidget(ceusAnalysis)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 341, 751))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.imageSelectionSidebar = QtWidgets.QFrame(self.sidebar)
        self.imageSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.imageSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.imageSelectionSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageSelectionSidebar.setObjectName("imageSelectionSidebar")
        self.imageSelectionLabelSidebar = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imageSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.imageSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignCenter)
        self.imageSelectionLabelSidebar.setObjectName("imageSelectionLabelSidebar")
        self.imageLabel = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imageLabel.setGeometry(QtCore.QRect(-60, 50, 191, 51))
        self.imageLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.imagePathInput = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imagePathInput.setGeometry(QtCore.QRect(100, 50, 241, 51))
        self.imagePathInput.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.imagePathInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.imagePathInput.setObjectName("imagePathInput")
        self.roiSidebar = QtWidgets.QFrame(self.sidebar)
        self.roiSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.roiSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.roiSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.roiSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.roiSidebar.setObjectName("roiSidebar")
        self.roiSidebarLabel = QtWidgets.QLabel(self.roiSidebar)
        self.roiSidebarLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.roiSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.roiSidebarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.roiSidebarLabel.setObjectName("roiSidebarLabel")
        self.rfAnalysisSidebar = QtWidgets.QFrame(self.sidebar)
        self.rfAnalysisSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.rfAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.rfAnalysisSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rfAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rfAnalysisSidebar.setObjectName("rfAnalysisSidebar")
        self.rfAnalysisLabel = QtWidgets.QLabel(self.rfAnalysisSidebar)
        self.rfAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.rfAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.rfAnalysisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rfAnalysisLabel.setObjectName("rfAnalysisLabel")
        self.ticAnalysisSidebar = QtWidgets.QFrame(self.sidebar)
        self.ticAnalysisSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.ticAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.ticAnalysisSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ticAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ticAnalysisSidebar.setObjectName("ticAnalysisSidebar")
        self.ticAnalysisLabel = QtWidgets.QLabel(self.ticAnalysisSidebar)
        self.ticAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.ticAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.ticAnalysisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ticAnalysisLabel.setObjectName("ticAnalysisLabel")
        self.analysisParamsSidebar = QtWidgets.QFrame(ceusAnalysis)
        self.analysisParamsSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisParamsSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisParamsSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.analysisParamsSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.analysisParamsSidebar.setObjectName("analysisParamsSidebar")
        self.analysisParamsLabel = QtWidgets.QLabel(self.analysisParamsSidebar)
        self.analysisParamsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisParamsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisParamsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.analysisParamsLabel.setObjectName("analysisParamsLabel")
        self.cePlane = QtWidgets.QLabel(ceusAnalysis)
        self.cePlane.setGeometry(QtCore.QRect(770, 150, 381, 351))
        self.cePlane.setText("")
        self.cePlane.setObjectName("cePlane")
        self.mcBmodeDisplayLabel = QtWidgets.QLabel(ceusAnalysis)
        self.mcBmodeDisplayLabel.setGeometry(QtCore.QRect(360, 150, 381, 351))
        self.mcBmodeDisplayLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.mcBmodeDisplayLabel.setText("")
        self.mcBmodeDisplayLabel.setObjectName("mcBmodeDisplayLabel")
        self.ceMaskLayer = QtWidgets.QLabel(ceusAnalysis)
        self.ceMaskLayer.setGeometry(QtCore.QRect(770, 150, 381, 351))
        self.ceMaskLayer.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.ceMaskLayer.setText("")
        self.ceMaskLayer.setObjectName("ceMaskLayer")
        self.mcCeDisplayLabel = QtWidgets.QLabel(ceusAnalysis)
        self.mcCeDisplayLabel.setGeometry(QtCore.QRect(770, 150, 381, 351))
        self.mcCeDisplayLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.mcCeDisplayLabel.setText("")
        self.mcCeDisplayLabel.setObjectName("mcCeDisplayLabel")
        self.backButton = QtWidgets.QPushButton(ceusAnalysis)
        self.backButton.setGeometry(QtCore.QRect(10, 690, 131, 41))
        self.backButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.backButton.setObjectName("backButton")
        self.curSliceSpinBox = QtWidgets.QSpinBox(ceusAnalysis)
        self.curSliceSpinBox.setGeometry(QtCore.QRect(410, 655, 48, 24))
        self.curSliceSpinBox.setStyleSheet("QSpinBox {\n"
"    background: white;\n"
"    color: black;\n"
"}")
        self.curSliceSpinBox.setObjectName("curSliceSpinBox")
        self.curSliceOfLabel_2 = QtWidgets.QLabel(ceusAnalysis)
        self.curSliceOfLabel_2.setGeometry(QtCore.QRect(410, 700, 41, 31))
        self.curSliceOfLabel_2.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.curSliceOfLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.curSliceOfLabel_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.curSliceOfLabel_2.setObjectName("curSliceOfLabel_2")
        self.totalSecondsLabel = QtWidgets.QLabel(ceusAnalysis)
        self.totalSecondsLabel.setGeometry(QtCore.QRect(445, 700, 61, 31))
        self.totalSecondsLabel.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.totalSecondsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.totalSecondsLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.totalSecondsLabel.setObjectName("totalSecondsLabel")
        self.curSecondLabel = QtWidgets.QLabel(ceusAnalysis)
        self.curSecondLabel.setGeometry(QtCore.QRect(350, 700, 61, 31))
        self.curSecondLabel.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.curSecondLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.curSecondLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.curSecondLabel.setObjectName("curSecondLabel")
        self.secondsLabel = QtWidgets.QLabel(ceusAnalysis)
        self.secondsLabel.setGeometry(QtCore.QRect(510, 700, 81, 31))
        self.secondsLabel.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.secondsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.secondsLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.secondsLabel.setObjectName("secondsLabel")
        self.constructRoiLabel = QtWidgets.QLabel(ceusAnalysis)
        self.constructRoiLabel.setGeometry(QtCore.QRect(540, -10, 431, 131))
        self.constructRoiLabel.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.constructRoiLabel.setTextFormat(QtCore.Qt.AutoText)
        self.constructRoiLabel.setScaledContents(False)
        self.constructRoiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.constructRoiLabel.setWordWrap(True)
        self.constructRoiLabel.setObjectName("constructRoiLabel")
        self.bmodeCoverLabel = QtWidgets.QLabel(ceusAnalysis)
        self.bmodeCoverLabel.setGeometry(QtCore.QRect(360, 150, 381, 351))
        self.bmodeCoverLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.bmodeCoverLabel.setText("")
        self.bmodeCoverLabel.setObjectName("bmodeCoverLabel")
        self.ceCoverLabel = QtWidgets.QLabel(ceusAnalysis)
        self.ceCoverLabel.setGeometry(QtCore.QRect(770, 150, 381, 351))
        self.ceCoverLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.ceCoverLabel.setText("")
        self.ceCoverLabel.setObjectName("ceCoverLabel")
        self.peVal = QtWidgets.QLabel(ceusAnalysis)
        self.peVal.setGeometry(QtCore.QRect(910, 590, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.peVal.setFont(font)
        self.peVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.peVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.peVal.setObjectName("peVal")
        self.tpLabel = QtWidgets.QLabel(ceusAnalysis)
        self.tpLabel.setGeometry(QtCore.QRect(820, 630, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tpLabel.setFont(font)
        self.tpLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.tpLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tpLabel.setObjectName("tpLabel")
        self.voiVolumeVal = QtWidgets.QLabel(ceusAnalysis)
        self.voiVolumeVal.setGeometry(QtCore.QRect(910, 690, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.voiVolumeVal.setFont(font)
        self.voiVolumeVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.voiVolumeVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.voiVolumeVal.setObjectName("voiVolumeVal")
        self.mttLabel = QtWidgets.QLabel(ceusAnalysis)
        self.mttLabel.setGeometry(QtCore.QRect(820, 610, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mttLabel.setFont(font)
        self.mttLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.mttLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mttLabel.setObjectName("mttLabel")
        self.tpVal = QtWidgets.QLabel(ceusAnalysis)
        self.tpVal.setGeometry(QtCore.QRect(910, 630, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tpVal.setFont(font)
        self.tpVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.tpVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tpVal.setObjectName("tpVal")
        self.voiVolumeLabel = QtWidgets.QLabel(ceusAnalysis)
        self.voiVolumeLabel.setGeometry(QtCore.QRect(820, 670, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.voiVolumeLabel.setFont(font)
        self.voiVolumeLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.voiVolumeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.voiVolumeLabel.setObjectName("voiVolumeLabel")
        self.tmppvLabel = QtWidgets.QLabel(ceusAnalysis)
        self.tmppvLabel.setGeometry(QtCore.QRect(820, 650, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tmppvLabel.setFont(font)
        self.tmppvLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.tmppvLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tmppvLabel.setObjectName("tmppvLabel")
        self.aucVal = QtWidgets.QLabel(ceusAnalysis)
        self.aucVal.setGeometry(QtCore.QRect(910, 570, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.aucVal.setFont(font)
        self.aucVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.aucVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.aucVal.setObjectName("aucVal")
        self.peLabel = QtWidgets.QLabel(ceusAnalysis)
        self.peLabel.setGeometry(QtCore.QRect(820, 590, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.peLabel.setFont(font)
        self.peLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.peLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.peLabel.setObjectName("peLabel")
        self.tmppvVal = QtWidgets.QLabel(ceusAnalysis)
        self.tmppvVal.setGeometry(QtCore.QRect(910, 650, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tmppvVal.setFont(font)
        self.tmppvVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.tmppvVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tmppvVal.setObjectName("tmppvVal")
        self.mttVal = QtWidgets.QLabel(ceusAnalysis)
        self.mttVal.setGeometry(QtCore.QRect(910, 610, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mttVal.setFont(font)
        self.mttVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.mttVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mttVal.setObjectName("mttVal")
        self.aucLabel = QtWidgets.QLabel(ceusAnalysis)
        self.aucLabel.setGeometry(QtCore.QRect(820, 570, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.aucLabel.setFont(font)
        self.aucLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.aucLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.aucLabel.setObjectName("aucLabel")
        self.curSliceTotal = QtWidgets.QLabel(ceusAnalysis)
        self.curSliceTotal.setGeometry(QtCore.QRect(490, 650, 61, 31))
        self.curSliceTotal.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.curSliceTotal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.curSliceTotal.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.curSliceTotal.setObjectName("curSliceTotal")
        self.saveDataButton = QtWidgets.QPushButton(ceusAnalysis)
        self.saveDataButton.setGeometry(QtCore.QRect(150, 640, 181, 41))
        self.saveDataButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.saveDataButton.setObjectName("saveDataButton")
        self.exportDataButton = QtWidgets.QPushButton(ceusAnalysis)
        self.exportDataButton.setGeometry(QtCore.QRect(150, 690, 181, 41))
        self.exportDataButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.exportDataButton.setObjectName("exportDataButton")
        self.displayTpButton = QtWidgets.QPushButton(ceusAnalysis)
        self.displayTpButton.setGeometry(QtCore.QRect(610, 660, 181, 31))
        self.displayTpButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.displayTpButton.setObjectName("displayTpButton")
        self.displayTmppvButton = QtWidgets.QPushButton(ceusAnalysis)
        self.displayTmppvButton.setGeometry(QtCore.QRect(610, 700, 181, 31))
        self.displayTmppvButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.displayTmppvButton.setObjectName("displayTmppvButton")
        self.displayMttButton = QtWidgets.QPushButton(ceusAnalysis)
        self.displayMttButton.setGeometry(QtCore.QRect(610, 620, 181, 31))
        self.displayMttButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.displayMttButton.setObjectName("displayMttButton")
        self.displayPeButton = QtWidgets.QPushButton(ceusAnalysis)
        self.displayPeButton.setGeometry(QtCore.QRect(610, 580, 181, 31))
        self.displayPeButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.displayPeButton.setObjectName("displayPeButton")
        self.displayAucButton = QtWidgets.QPushButton(ceusAnalysis)
        self.displayAucButton.setGeometry(QtCore.QRect(610, 540, 181, 31))
        self.displayAucButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.displayAucButton.setObjectName("displayAucButton")
        self.indMttLabel = QtWidgets.QLabel(ceusAnalysis)
        self.indMttLabel.setGeometry(QtCore.QRect(1010, 610, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indMttLabel.setFont(font)
        self.indMttLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indMttLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indMttLabel.setObjectName("indMttLabel")
        self.indAucVal = QtWidgets.QLabel(ceusAnalysis)
        self.indAucVal.setGeometry(QtCore.QRect(1100, 570, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indAucVal.setFont(font)
        self.indAucVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indAucVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indAucVal.setObjectName("indAucVal")
        self.indPeLabel = QtWidgets.QLabel(ceusAnalysis)
        self.indPeLabel.setGeometry(QtCore.QRect(1010, 590, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indPeLabel.setFont(font)
        self.indPeLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indPeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indPeLabel.setObjectName("indPeLabel")
        self.indPeVal = QtWidgets.QLabel(ceusAnalysis)
        self.indPeVal.setGeometry(QtCore.QRect(1100, 590, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indPeVal.setFont(font)
        self.indPeVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indPeVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indPeVal.setObjectName("indPeVal")
        self.indMttVal = QtWidgets.QLabel(ceusAnalysis)
        self.indMttVal.setGeometry(QtCore.QRect(1100, 610, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indMttVal.setFont(font)
        self.indMttVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indMttVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indMttVal.setObjectName("indMttVal")
        self.indTmppvVal = QtWidgets.QLabel(ceusAnalysis)
        self.indTmppvVal.setGeometry(QtCore.QRect(1100, 650, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indTmppvVal.setFont(font)
        self.indTmppvVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indTmppvVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indTmppvVal.setObjectName("indTmppvVal")
        self.indTpVal = QtWidgets.QLabel(ceusAnalysis)
        self.indTpVal.setGeometry(QtCore.QRect(1100, 630, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indTpVal.setFont(font)
        self.indTpVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indTpVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indTpVal.setObjectName("indTpVal")
        self.indAucLabel = QtWidgets.QLabel(ceusAnalysis)
        self.indAucLabel.setGeometry(QtCore.QRect(1010, 570, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indAucLabel.setFont(font)
        self.indAucLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indAucLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indAucLabel.setObjectName("indAucLabel")
        self.indTpLabel = QtWidgets.QLabel(ceusAnalysis)
        self.indTpLabel.setGeometry(QtCore.QRect(1010, 630, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indTpLabel.setFont(font)
        self.indTpLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indTpLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indTpLabel.setObjectName("indTpLabel")
        self.indTmppvLabel = QtWidgets.QLabel(ceusAnalysis)
        self.indTmppvLabel.setGeometry(QtCore.QRect(1010, 650, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indTmppvLabel.setFont(font)
        self.indTmppvLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indTmppvLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indTmppvLabel.setObjectName("indTmppvLabel")
        self.resultsLabel = QtWidgets.QLabel(ceusAnalysis)
        self.resultsLabel.setGeometry(QtCore.QRect(800, 520, 361, 51))
        self.resultsLabel.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.resultsLabel.setTextFormat(QtCore.Qt.AutoText)
        self.resultsLabel.setScaledContents(False)
        self.resultsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultsLabel.setWordWrap(True)
        self.resultsLabel.setObjectName("resultsLabel")

        self.retranslateUi(ceusAnalysis)
        QtCore.QMetaObject.connectSlotsByName(ceusAnalysis)

    def retranslateUi(self, ceusAnalysis):
        _translate = QtCore.QCoreApplication.translate
        ceusAnalysis.setWindowTitle(_translate("ceusAnalysis", "Select Region of Interest"))
        self.axialPlaneLabel.setText(_translate("ceusAnalysis", "B-Mode"))
        self.sagittalPlaneLabel.setText(_translate("ceusAnalysis", "Contrast-Enhanced Image"))
        self.curSliceLabel.setText(_translate("ceusAnalysis", "Current Frame:"))
        self.curSliceOfLabel.setText(_translate("ceusAnalysis", "of"))
        self.sidebar.setToolTip(_translate("ceusAnalysis", "<html><head/><body><p><br/></p></body></html>"))
        self.imageSelectionLabelSidebar.setText(_translate("ceusAnalysis", "Image Selection:"))
        self.imageLabel.setText(_translate("ceusAnalysis", "Image:"))
        self.imagePathInput.setText(_translate("ceusAnalysis", "Sample filename "))
        self.roiSidebarLabel.setText(_translate("ceusAnalysis", "Region of Interest (ROI) Selection"))
        self.rfAnalysisLabel.setText(_translate("ceusAnalysis", "Export Results"))
        self.ticAnalysisLabel.setText(_translate("ceusAnalysis", "Contrast-Enhanced Ultrasound\n"
"(CEUS) Analysis"))
        self.analysisParamsLabel.setText(_translate("ceusAnalysis", "TIC Modification"))
        self.backButton.setText(_translate("ceusAnalysis", "Back"))
        self.curSliceOfLabel_2.setText(_translate("ceusAnalysis", "of"))
        self.totalSecondsLabel.setText(_translate("ceusAnalysis", "0"))
        self.curSecondLabel.setText(_translate("ceusAnalysis", "0"))
        self.secondsLabel.setText(_translate("ceusAnalysis", "seconds"))
        self.constructRoiLabel.setText(_translate("ceusAnalysis", "Construct Region of Interest (ROI):"))
        self.peVal.setText(_translate("ceusAnalysis", "0"))
        self.tpLabel.setText(_translate("ceusAnalysis", "Av.  TP"))
        self.voiVolumeVal.setText(_translate("ceusAnalysis", "0"))
        self.mttLabel.setText(_translate("ceusAnalysis", "Av.  MTT"))
        self.tpVal.setText(_translate("ceusAnalysis", "0"))
        self.voiVolumeLabel.setText(_translate("ceusAnalysis", "ROI Area\n"
"(mm^2)"))
        self.tmppvLabel.setText(_translate("ceusAnalysis", "Av.  TMPPV"))
        self.aucVal.setText(_translate("ceusAnalysis", "0"))
        self.peLabel.setText(_translate("ceusAnalysis", "Av.  PE"))
        self.tmppvVal.setText(_translate("ceusAnalysis", "0"))
        self.mttVal.setText(_translate("ceusAnalysis", "0"))
        self.aucLabel.setText(_translate("ceusAnalysis", "Av.  AUC"))
        self.curSliceTotal.setText(_translate("ceusAnalysis", "0"))
        self.saveDataButton.setText(_translate("ceusAnalysis", "Save Data"))
        self.exportDataButton.setText(_translate("ceusAnalysis", "Export Data"))
        self.displayTpButton.setText(_translate("ceusAnalysis", "Display TP"))
        self.displayTmppvButton.setText(_translate("ceusAnalysis", "Display TMPPV"))
        self.displayMttButton.setText(_translate("ceusAnalysis", "Display MTT"))
        self.displayPeButton.setText(_translate("ceusAnalysis", "Display PE"))
        self.displayAucButton.setText(_translate("ceusAnalysis", "Display AUC"))
        self.indMttLabel.setText(_translate("ceusAnalysis", "Ind.  MTT"))
        self.indAucVal.setText(_translate("ceusAnalysis", "0"))
        self.indPeLabel.setText(_translate("ceusAnalysis", "Ind.  PE"))
        self.indPeVal.setText(_translate("ceusAnalysis", "0"))
        self.indMttVal.setText(_translate("ceusAnalysis", "0"))
        self.indTmppvVal.setText(_translate("ceusAnalysis", "0"))
        self.indTpVal.setText(_translate("ceusAnalysis", "0"))
        self.indAucLabel.setText(_translate("ceusAnalysis", "Ind.  AUC"))
        self.indTpLabel.setText(_translate("ceusAnalysis", "Ind.  TP"))
        self.indTmppvLabel.setText(_translate("ceusAnalysis", "Ind.  TMPPV"))
        self.resultsLabel.setText(_translate("ceusAnalysis", "Results"))
