# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CeusMcTool2d/roiSelection.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_constructRoi(object):
    def setupUi(self, constructRoi):
        constructRoi.setObjectName("constructRoi")
        constructRoi.resize(1175, 749)
        constructRoi.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.axialPlaneLabel = QtWidgets.QLabel(constructRoi)
        self.axialPlaneLabel.setGeometry(QtCore.QRect(410, 100, 271, 51))
        self.axialPlaneLabel.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.axialPlaneLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.axialPlaneLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.axialPlaneLabel.setObjectName("axialPlaneLabel")
        self.sagittalPlaneLabel = QtWidgets.QLabel(constructRoi)
        self.sagittalPlaneLabel.setGeometry(QtCore.QRect(830, 100, 271, 51))
        self.sagittalPlaneLabel.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.sagittalPlaneLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sagittalPlaneLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.sagittalPlaneLabel.setObjectName("sagittalPlaneLabel")
        self.curSliceLabel = QtWidgets.QLabel(constructRoi)
        self.curSliceLabel.setGeometry(QtCore.QRect(350, 530, 361, 51))
        self.curSliceLabel.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.curSliceLabel.setTextFormat(QtCore.Qt.AutoText)
        self.curSliceLabel.setScaledContents(False)
        self.curSliceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.curSliceLabel.setWordWrap(True)
        self.curSliceLabel.setObjectName("curSliceLabel")
        self.curSliceSlider = QtWidgets.QSlider(constructRoi)
        self.curSliceSlider.setGeometry(QtCore.QRect(369, 590, 191, 41))
        self.curSliceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.curSliceSlider.setObjectName("curSliceSlider")
        self.curSliceOfLabel = QtWidgets.QLabel(constructRoi)
        self.curSliceOfLabel.setGeometry(QtCore.QRect(665, 595, 41, 31))
        self.curSliceOfLabel.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.curSliceOfLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.curSliceOfLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.curSliceOfLabel.setObjectName("curSliceOfLabel")
        self.curSliceTotal = QtWidgets.QLabel(constructRoi)
        self.curSliceTotal.setGeometry(QtCore.QRect(700, 595, 61, 31))
        self.curSliceTotal.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.curSliceTotal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.curSliceTotal.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.curSliceTotal.setObjectName("curSliceTotal")
        self.sidebar = QtWidgets.QWidget(constructRoi)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 341, 751))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.imageSelectionSidebar = QtWidgets.QFrame(self.sidebar)
        self.imageSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.imageSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.imageSelectionSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageSelectionSidebar.setObjectName("imageSelectionSidebar")
        self.imageSelectionLabelSidebar = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imageSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.imageSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignCenter)
        self.imageSelectionLabelSidebar.setObjectName("imageSelectionLabelSidebar")
        self.imageLabel = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imageLabel.setGeometry(QtCore.QRect(-60, 50, 191, 51))
        self.imageLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.imagePathInput = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imagePathInput.setGeometry(QtCore.QRect(100, 50, 241, 51))
        self.imagePathInput.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.imagePathInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.imagePathInput.setObjectName("imagePathInput")
        self.roiSidebar = QtWidgets.QFrame(self.sidebar)
        self.roiSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.roiSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.roiSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.roiSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.roiSidebar.setObjectName("roiSidebar")
        self.roiSidebarLabel = QtWidgets.QLabel(self.roiSidebar)
        self.roiSidebarLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.roiSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.roiSidebarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.roiSidebarLabel.setObjectName("roiSidebarLabel")
        self.rfAnalysisSidebar = QtWidgets.QFrame(self.sidebar)
        self.rfAnalysisSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.rfAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.rfAnalysisSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rfAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rfAnalysisSidebar.setObjectName("rfAnalysisSidebar")
        self.rfAnalysisLabel = QtWidgets.QLabel(self.rfAnalysisSidebar)
        self.rfAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.rfAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.rfAnalysisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rfAnalysisLabel.setObjectName("rfAnalysisLabel")
        self.ticAnalysisSidebar = QtWidgets.QFrame(self.sidebar)
        self.ticAnalysisSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.ticAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.ticAnalysisSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ticAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ticAnalysisSidebar.setObjectName("ticAnalysisSidebar")
        self.ticAnalysisLabel = QtWidgets.QLabel(self.ticAnalysisSidebar)
        self.ticAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.ticAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.ticAnalysisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ticAnalysisLabel.setObjectName("ticAnalysisLabel")
        self.analysisParamsSidebar = QtWidgets.QFrame(constructRoi)
        self.analysisParamsSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisParamsSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisParamsSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.analysisParamsSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.analysisParamsSidebar.setObjectName("analysisParamsSidebar")
        self.analysisParamsLabel = QtWidgets.QLabel(self.analysisParamsSidebar)
        self.analysisParamsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisParamsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisParamsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.analysisParamsLabel.setObjectName("analysisParamsLabel")
        self.bmodePlane = QtWidgets.QLabel(constructRoi)
        self.bmodePlane.setGeometry(QtCore.QRect(360, 150, 381, 351))
        self.bmodePlane.setText("")
        self.bmodePlane.setObjectName("bmodePlane")
        self.bmodeMaskLayer = QtWidgets.QLabel(constructRoi)
        self.bmodeMaskLayer.setGeometry(QtCore.QRect(360, 150, 381, 351))
        self.bmodeMaskLayer.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.bmodeMaskLayer.setText("")
        self.bmodeMaskLayer.setObjectName("bmodeMaskLayer")
        self.cePlane = QtWidgets.QLabel(constructRoi)
        self.cePlane.setGeometry(QtCore.QRect(770, 150, 381, 351))
        self.cePlane.setText("")
        self.cePlane.setObjectName("cePlane")
        self.mcBmodeDisplayLabel = QtWidgets.QLabel(constructRoi)
        self.mcBmodeDisplayLabel.setGeometry(QtCore.QRect(360, 150, 381, 351))
        self.mcBmodeDisplayLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.mcBmodeDisplayLabel.setText("")
        self.mcBmodeDisplayLabel.setObjectName("mcBmodeDisplayLabel")
        self.ceMaskLayer = QtWidgets.QLabel(constructRoi)
        self.ceMaskLayer.setGeometry(QtCore.QRect(770, 150, 381, 351))
        self.ceMaskLayer.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.ceMaskLayer.setText("")
        self.ceMaskLayer.setObjectName("ceMaskLayer")
        self.mcCeDisplayLabel = QtWidgets.QLabel(constructRoi)
        self.mcCeDisplayLabel.setGeometry(QtCore.QRect(770, 150, 381, 351))
        self.mcCeDisplayLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.mcCeDisplayLabel.setText("")
        self.mcCeDisplayLabel.setObjectName("mcCeDisplayLabel")
        self.backButton = QtWidgets.QPushButton(constructRoi)
        self.backButton.setGeometry(QtCore.QRect(10, 690, 131, 41))
        self.backButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.backButton.setObjectName("backButton")
        self.curSliceSpinBox = QtWidgets.QSpinBox(constructRoi)
        self.curSliceSpinBox.setGeometry(QtCore.QRect(620, 600, 48, 24))
        self.curSliceSpinBox.setStyleSheet("QSpinBox {\n"
"    background: white;\n"
"    color: black;\n"
"}")
        self.curSliceSpinBox.setObjectName("curSliceSpinBox")
        self.curSliceOfLabel_2 = QtWidgets.QLabel(constructRoi)
        self.curSliceOfLabel_2.setGeometry(QtCore.QRect(480, 660, 41, 31))
        self.curSliceOfLabel_2.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.curSliceOfLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.curSliceOfLabel_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.curSliceOfLabel_2.setObjectName("curSliceOfLabel_2")
        self.totalSecondsLabel = QtWidgets.QLabel(constructRoi)
        self.totalSecondsLabel.setGeometry(QtCore.QRect(515, 660, 61, 31))
        self.totalSecondsLabel.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.totalSecondsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.totalSecondsLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.totalSecondsLabel.setObjectName("totalSecondsLabel")
        self.curSecondLabel = QtWidgets.QLabel(constructRoi)
        self.curSecondLabel.setGeometry(QtCore.QRect(420, 660, 61, 31))
        self.curSecondLabel.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.curSecondLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.curSecondLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.curSecondLabel.setObjectName("curSecondLabel")
        self.secondsLabel = QtWidgets.QLabel(constructRoi)
        self.secondsLabel.setGeometry(QtCore.QRect(580, 660, 81, 31))
        self.secondsLabel.setStyleSheet("QLabel {\n"
"    font-size: 17px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.secondsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.secondsLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.secondsLabel.setObjectName("secondsLabel")
        self.constructRoiLabel = QtWidgets.QLabel(constructRoi)
        self.constructRoiLabel.setGeometry(QtCore.QRect(540, -10, 431, 131))
        self.constructRoiLabel.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.constructRoiLabel.setTextFormat(QtCore.Qt.AutoText)
        self.constructRoiLabel.setScaledContents(False)
        self.constructRoiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.constructRoiLabel.setWordWrap(True)
        self.constructRoiLabel.setObjectName("constructRoiLabel")
        self.undoLastPtButton = QtWidgets.QPushButton(constructRoi)
        self.undoLastPtButton.setGeometry(QtCore.QRect(970, 570, 171, 41))
        self.undoLastPtButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.undoLastPtButton.setCheckable(False)
        self.undoLastPtButton.setObjectName("undoLastPtButton")
        self.closeRoiButton = QtWidgets.QPushButton(constructRoi)
        self.closeRoiButton.setGeometry(QtCore.QRect(780, 630, 171, 41))
        self.closeRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.closeRoiButton.setCheckable(False)
        self.closeRoiButton.setObjectName("closeRoiButton")
        self.redrawRoiButton = QtWidgets.QPushButton(constructRoi)
        self.redrawRoiButton.setGeometry(QtCore.QRect(780, 630, 171, 41))
        self.redrawRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.redrawRoiButton.setCheckable(False)
        self.redrawRoiButton.setObjectName("redrawRoiButton")
        self.drawRoiButton = QtWidgets.QPushButton(constructRoi)
        self.drawRoiButton.setGeometry(QtCore.QRect(780, 570, 171, 41))
        self.drawRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 16px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.drawRoiButton.setCheckable(True)
        self.drawRoiButton.setChecked(False)
        self.drawRoiButton.setObjectName("drawRoiButton")
        self.fitToRoiButton = QtWidgets.QPushButton(constructRoi)
        self.fitToRoiButton.setGeometry(QtCore.QRect(970, 630, 171, 41))
        self.fitToRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.fitToRoiButton.setCheckable(False)
        self.fitToRoiButton.setObjectName("fitToRoiButton")
        self.acceptGeneratedRoiButton = QtWidgets.QPushButton(constructRoi)
        self.acceptGeneratedRoiButton.setGeometry(QtCore.QRect(970, 600, 171, 41))
        self.acceptGeneratedRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.acceptGeneratedRoiButton.setCheckable(True)
        self.acceptGeneratedRoiButton.setChecked(False)
        self.acceptGeneratedRoiButton.setObjectName("acceptGeneratedRoiButton")
        self.roiFitNoteLabel = QtWidgets.QLabel(constructRoi)
        self.roiFitNoteLabel.setGeometry(QtCore.QRect(780, 690, 341, 41))
        self.roiFitNoteLabel.setStyleSheet("QLabel {\n"
"    color: rgb(255, 0, 23);\n"
"    font-size: 20px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.roiFitNoteLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.roiFitNoteLabel.setObjectName("roiFitNoteLabel")
        self.bmodeCoverLabel = QtWidgets.QLabel(constructRoi)
        self.bmodeCoverLabel.setGeometry(QtCore.QRect(360, 150, 381, 351))
        self.bmodeCoverLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.bmodeCoverLabel.setText("")
        self.bmodeCoverLabel.setObjectName("bmodeCoverLabel")
        self.ceCoverLabel = QtWidgets.QLabel(constructRoi)
        self.ceCoverLabel.setGeometry(QtCore.QRect(770, 150, 381, 351))
        self.ceCoverLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.ceCoverLabel.setText("")
        self.ceCoverLabel.setObjectName("ceCoverLabel")
        self.undoRoiButton = QtWidgets.QPushButton(constructRoi)
        self.undoRoiButton.setGeometry(QtCore.QRect(780, 600, 171, 41))
        self.undoRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.undoRoiButton.setCheckable(True)
        self.undoRoiButton.setChecked(False)
        self.undoRoiButton.setObjectName("undoRoiButton")
        self.newRoiButton = QtWidgets.QPushButton(constructRoi)
        self.newRoiButton.setGeometry(QtCore.QRect(780, 600, 171, 41))
        self.newRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.newRoiButton.setCheckable(True)
        self.newRoiButton.setChecked(False)
        self.newRoiButton.setObjectName("newRoiButton")
        self.loadRoiButton = QtWidgets.QPushButton(constructRoi)
        self.loadRoiButton.setGeometry(QtCore.QRect(970, 600, 171, 41))
        self.loadRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.loadRoiButton.setCheckable(True)
        self.loadRoiButton.setChecked(False)
        self.loadRoiButton.setObjectName("loadRoiButton")

        self.retranslateUi(constructRoi)
        QtCore.QMetaObject.connectSlotsByName(constructRoi)

    def retranslateUi(self, constructRoi):
        _translate = QtCore.QCoreApplication.translate
        constructRoi.setWindowTitle(_translate("constructRoi", "Select Region of Interest"))
        self.axialPlaneLabel.setText(_translate("constructRoi", "B-Mode"))
        self.sagittalPlaneLabel.setText(_translate("constructRoi", "Contrast-Enhanced Image"))
        self.curSliceLabel.setText(_translate("constructRoi", "Current Frame:"))
        self.curSliceOfLabel.setText(_translate("constructRoi", "of"))
        self.curSliceTotal.setText(_translate("constructRoi", "0"))
        self.sidebar.setToolTip(_translate("constructRoi", "<html><head/><body><p><br/></p></body></html>"))
        self.imageSelectionLabelSidebar.setText(_translate("constructRoi", "Image Selection:"))
        self.imageLabel.setText(_translate("constructRoi", "Image:"))
        self.imagePathInput.setText(_translate("constructRoi", "Sample filename "))
        self.roiSidebarLabel.setText(_translate("constructRoi", "Region of Interest (ROI) Selection"))
        self.rfAnalysisLabel.setText(_translate("constructRoi", "Export Results"))
        self.ticAnalysisLabel.setText(_translate("constructRoi", "Contrast-Enhanced Ultrasound\n"
"(CEUS) Analysis"))
        self.analysisParamsLabel.setText(_translate("constructRoi", "TIC Modification"))
        self.backButton.setText(_translate("constructRoi", "Back"))
        self.curSliceOfLabel_2.setText(_translate("constructRoi", "of"))
        self.totalSecondsLabel.setText(_translate("constructRoi", "0"))
        self.curSecondLabel.setText(_translate("constructRoi", "0"))
        self.secondsLabel.setText(_translate("constructRoi", "seconds"))
        self.constructRoiLabel.setText(_translate("constructRoi", "Construct Region of Interest (ROI):"))
        self.undoLastPtButton.setText(_translate("constructRoi", "Undo Last Point"))
        self.closeRoiButton.setText(_translate("constructRoi", "Close ROI"))
        self.redrawRoiButton.setText(_translate("constructRoi", "Redraw ROI"))
        self.drawRoiButton.setText(_translate("constructRoi", "Draw ROI"))
        self.fitToRoiButton.setText(_translate("constructRoi", "Fit to ROI"))
        self.acceptGeneratedRoiButton.setText(_translate("constructRoi", "Accept Generated ROI"))
        self.roiFitNoteLabel.setText(_translate("constructRoi", "NOTE: Will fit to ROI using current\n"
"frame as reference"))
        self.undoRoiButton.setText(_translate("constructRoi", "Undo"))
        self.newRoiButton.setText(_translate("constructRoi", "New ROI"))
        self.loadRoiButton.setText(_translate("constructRoi", "Load ROI"))
