# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UtcTool2d/analysisParamsSelection.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_analysisParams(object):
    def setupUi(self, analysisParams):
        analysisParams.setObjectName("analysisParams")
        analysisParams.resize(1175, 749)
        analysisParams.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.sidebar = QtWidgets.QWidget(analysisParams)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 341, 751))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.imageSelectionSidebar = QtWidgets.QFrame(self.sidebar)
        self.imageSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.imageSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.imageSelectionSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageSelectionSidebar.setObjectName("imageSelectionSidebar")
        self.imageSelectionLabelSidebar = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imageSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.imageSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignCenter)
        self.imageSelectionLabelSidebar.setObjectName("imageSelectionLabelSidebar")
        self.imageLabel = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imageLabel.setGeometry(QtCore.QRect(-60, 40, 191, 51))
        self.imageLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.phantomLabel = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.phantomLabel.setGeometry(QtCore.QRect(-50, 70, 191, 51))
        self.phantomLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold\n"
"}")
        self.phantomLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.phantomLabel.setObjectName("phantomLabel")
        self.imagePathInput = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imagePathInput.setGeometry(QtCore.QRect(100, 40, 241, 51))
        self.imagePathInput.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.imagePathInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.imagePathInput.setObjectName("imagePathInput")
        self.phantomPathInput = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.phantomPathInput.setGeometry(QtCore.QRect(100, 70, 241, 51))
        self.phantomPathInput.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.phantomPathInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.phantomPathInput.setObjectName("phantomPathInput")
        self.roiSidebar = QtWidgets.QFrame(self.sidebar)
        self.roiSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.roiSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.roiSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.roiSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.roiSidebar.setObjectName("roiSidebar")
        self.roiSidebarLabel = QtWidgets.QLabel(self.roiSidebar)
        self.roiSidebarLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.roiSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.roiSidebarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.roiSidebarLabel.setObjectName("roiSidebarLabel")
        self.analysisParamsSidebar = QtWidgets.QFrame(self.sidebar)
        self.analysisParamsSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisParamsSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisParamsSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.analysisParamsSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.analysisParamsSidebar.setObjectName("analysisParamsSidebar")
        self.analysisParamsLabel = QtWidgets.QLabel(self.analysisParamsSidebar)
        self.analysisParamsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisParamsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisParamsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.analysisParamsLabel.setObjectName("analysisParamsLabel")
        self.rfAnalysisSidebar = QtWidgets.QFrame(self.sidebar)
        self.rfAnalysisSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.rfAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.rfAnalysisSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rfAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rfAnalysisSidebar.setObjectName("rfAnalysisSidebar")
        self.rfAnalysisLabel = QtWidgets.QLabel(self.rfAnalysisSidebar)
        self.rfAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.rfAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.rfAnalysisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rfAnalysisLabel.setObjectName("rfAnalysisLabel")
        self.analysisParamsLabel_2 = QtWidgets.QLabel(analysisParams)
        self.analysisParamsLabel_2.setGeometry(QtCore.QRect(460, 10, 571, 131))
        self.analysisParamsLabel_2.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.analysisParamsLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.analysisParamsLabel_2.setScaledContents(False)
        self.analysisParamsLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.analysisParamsLabel_2.setWordWrap(True)
        self.analysisParamsLabel_2.setObjectName("analysisParamsLabel_2")
        self.continueButton = QtWidgets.QPushButton(analysisParams)
        self.continueButton.setGeometry(QtCore.QRect(670, 580, 171, 41))
        self.continueButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.continueButton.setObjectName("continueButton")
        self.exportResultsSidebar = QtWidgets.QFrame(analysisParams)
        self.exportResultsSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.exportResultsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.exportResultsSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.exportResultsSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exportResultsSidebar.setObjectName("exportResultsSidebar")
        self.exportResultsLabel = QtWidgets.QLabel(self.exportResultsSidebar)
        self.exportResultsLabel.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.exportResultsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.exportResultsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.exportResultsLabel.setObjectName("exportResultsLabel")
        self.backButton = QtWidgets.QPushButton(analysisParams)
        self.backButton.setGeometry(QtCore.QRect(10, 690, 131, 41))
        self.backButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.backButton.setObjectName("backButton")
        self.axOverlapVal = QtWidgets.QSpinBox(analysisParams)
        self.axOverlapVal.setGeometry(QtCore.QRect(1050, 265, 51, 31))
        self.axOverlapVal.setStyleSheet("QSpinBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"}")
        self.axOverlapVal.setObjectName("axOverlapVal")
        self.latWinSizeVal = QtWidgets.QDoubleSpinBox(analysisParams)
        self.latWinSizeVal.setGeometry(QtCore.QRect(660, 350, 61, 21))
        self.latWinSizeVal.setStyleSheet("QDoubleSpinBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"}")
        self.latWinSizeVal.setObjectName("latWinSizeVal")
        self.windowThresholdLabel = QtWidgets.QLabel(analysisParams)
        self.windowThresholdLabel.setGeometry(QtCore.QRect(570, 440, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.windowThresholdLabel.setFont(font)
        self.windowThresholdLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.windowThresholdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.windowThresholdLabel.setObjectName("windowThresholdLabel")
        self.axWinSizeVal = QtWidgets.QDoubleSpinBox(analysisParams)
        self.axWinSizeVal.setGeometry(QtCore.QRect(660, 270, 61, 21))
        self.axWinSizeVal.setStyleSheet("QDoubleSpinBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"}")
        self.axWinSizeVal.setObjectName("axWinSizeVal")
        self.latWinSizeLabel = QtWidgets.QLabel(analysisParams)
        self.latWinSizeLabel.setGeometry(QtCore.QRect(390, 330, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.latWinSizeLabel.setFont(font)
        self.latWinSizeLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.latWinSizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.latWinSizeLabel.setObjectName("latWinSizeLabel")
        self.imageDepthVal = QtWidgets.QLabel(analysisParams)
        self.imageDepthVal.setGeometry(QtCore.QRect(640, 150, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.imageDepthVal.setFont(font)
        self.imageDepthVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.imageDepthVal.setAlignment(QtCore.Qt.AlignCenter)
        self.imageDepthVal.setObjectName("imageDepthVal")
        self.latOverlapVal = QtWidgets.QSpinBox(analysisParams)
        self.latOverlapVal.setGeometry(QtCore.QRect(1050, 340, 51, 31))
        self.latOverlapVal.setStyleSheet("QSpinBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"}")
        self.latOverlapVal.setObjectName("latOverlapVal")
        self.axWinSizeLabel = QtWidgets.QLabel(analysisParams)
        self.axWinSizeLabel.setGeometry(QtCore.QRect(390, 250, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.axWinSizeLabel.setFont(font)
        self.axWinSizeLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.axWinSizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.axWinSizeLabel.setObjectName("axWinSizeLabel")
        self.imageDepthLabel = QtWidgets.QLabel(analysisParams)
        self.imageDepthLabel.setGeometry(QtCore.QRect(420, 150, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.imageDepthLabel.setFont(font)
        self.imageDepthLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.imageDepthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageDepthLabel.setObjectName("imageDepthLabel")
        self.latOverlapLabel = QtWidgets.QLabel(analysisParams)
        self.latOverlapLabel.setGeometry(QtCore.QRect(780, 330, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.latOverlapLabel.setFont(font)
        self.latOverlapLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.latOverlapLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.latOverlapLabel.setObjectName("latOverlapLabel")
        self.windowThresholdVal = QtWidgets.QSpinBox(analysisParams)
        self.windowThresholdVal.setGeometry(QtCore.QRect(840, 450, 51, 31))
        self.windowThresholdVal.setStyleSheet("QSpinBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"}")
        self.windowThresholdVal.setObjectName("windowThresholdVal")
        self.axOverlapLabel = QtWidgets.QLabel(analysisParams)
        self.axOverlapLabel.setGeometry(QtCore.QRect(780, 250, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.axOverlapLabel.setFont(font)
        self.axOverlapLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.axOverlapLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.axOverlapLabel.setObjectName("axOverlapLabel")
        self.imageWidthVal = QtWidgets.QLabel(analysisParams)
        self.imageWidthVal.setGeometry(QtCore.QRect(990, 150, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.imageWidthVal.setFont(font)
        self.imageWidthVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.imageWidthVal.setAlignment(QtCore.Qt.AlignCenter)
        self.imageWidthVal.setObjectName("imageWidthVal")
        self.imageWidthLabel = QtWidgets.QLabel(analysisParams)
        self.imageWidthLabel.setGeometry(QtCore.QRect(780, 150, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.imageWidthLabel.setFont(font)
        self.imageWidthLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.imageWidthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageWidthLabel.setObjectName("imageWidthLabel")

        self.retranslateUi(analysisParams)
        QtCore.QMetaObject.connectSlotsByName(analysisParams)

    def retranslateUi(self, analysisParams):
        _translate = QtCore.QCoreApplication.translate
        analysisParams.setWindowTitle(_translate("analysisParams", "Select Region of Interest"))
        self.sidebar.setToolTip(_translate("analysisParams", "<html><head/><body><p><br/></p></body></html>"))
        self.imageSelectionLabelSidebar.setText(_translate("analysisParams", "Image Selection:"))
        self.imageLabel.setText(_translate("analysisParams", "Image:"))
        self.phantomLabel.setText(_translate("analysisParams", "Phantom:"))
        self.imagePathInput.setText(_translate("analysisParams", "Sample filename "))
        self.phantomPathInput.setText(_translate("analysisParams", "Sample filename "))
        self.roiSidebarLabel.setText(_translate("analysisParams", "Region of Interest (ROI) Selection"))
        self.analysisParamsLabel.setText(_translate("analysisParams", "Analysis Parameter Selection"))
        self.rfAnalysisLabel.setText(_translate("analysisParams", "Radio Frequency Data Analysis"))
        self.analysisParamsLabel_2.setText(_translate("analysisParams", "Select Radio Frequency Analysis Parameters:"))
        self.continueButton.setText(_translate("analysisParams", "Continue"))
        self.exportResultsLabel.setText(_translate("analysisParams", "Export Results"))
        self.backButton.setText(_translate("analysisParams", "Back"))
        self.windowThresholdLabel.setText(_translate("analysisParams", "Window Threshold (%)"))
        self.latWinSizeLabel.setText(_translate("analysisParams", "Lateral Window Size (mm)"))
        self.imageDepthVal.setText(_translate("analysisParams", "1000"))
        self.axWinSizeLabel.setText(_translate("analysisParams", "Axial Window Size (mm)"))
        self.imageDepthLabel.setText(_translate("analysisParams", "Image Depth (mm)"))
        self.latOverlapLabel.setText(_translate("analysisParams", "Lateral Overlap (%)"))
        self.axOverlapLabel.setText(_translate("analysisParams", "Axial Overlap (%)"))
        self.imageWidthVal.setText(_translate("analysisParams", "1000"))
        self.imageWidthLabel.setText(_translate("analysisParams", "Image Width (mm)"))
