# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UtcTool2d/editImageDisplay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editBmode(object):
    def setupUi(self, editBmode):
        editBmode.setObjectName("editBmode")
        editBmode.resize(406, 300)
        editBmode.setStyleSheet("QWidget {\n"
"    background-color: rgb(42, 42, 42);\n"
"}")
        self.editImageDisplayLabel = QtWidgets.QLabel(editBmode)
        self.editImageDisplayLabel.setGeometry(QtCore.QRect(-10, -20, 431, 131))
        self.editImageDisplayLabel.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.editImageDisplayLabel.setTextFormat(QtCore.Qt.AutoText)
        self.editImageDisplayLabel.setScaledContents(False)
        self.editImageDisplayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.editImageDisplayLabel.setWordWrap(True)
        self.editImageDisplayLabel.setObjectName("editImageDisplayLabel")
        self.contrastValDisplay = QtWidgets.QProgressBar(editBmode)
        self.contrastValDisplay.setGeometry(QtCore.QRect(190, 110, 201, 16))
        self.contrastValDisplay.setStyleSheet("QProgressBar {\n"
"     border: 2px solid grey;\n"
"     border-radius: 5px;\n"
"     background-color: rgb(229, 229, 229);\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: rgb(90, 37, 255);;\n"
"     width: 20px;\n"
"    font-size: 0px;\n"
" }")
        self.contrastValDisplay.setProperty("value", 24)
        self.contrastValDisplay.setObjectName("contrastValDisplay")
        self.brightnessValDisplay = QtWidgets.QProgressBar(editBmode)
        self.brightnessValDisplay.setGeometry(QtCore.QRect(190, 170, 201, 16))
        self.brightnessValDisplay.setStyleSheet("QProgressBar {\n"
"     border: 2px solid grey;\n"
"     border-radius: 5px;\n"
"     background-color: rgb(229, 229, 229);\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: rgb(90, 37, 255);;\n"
"     width: 20px;\n"
"    font-size: 0px;\n"
" }")
        self.brightnessValDisplay.setProperty("value", 24)
        self.brightnessValDisplay.setObjectName("brightnessValDisplay")
        self.sharpnessValDisplay = QtWidgets.QProgressBar(editBmode)
        self.sharpnessValDisplay.setGeometry(QtCore.QRect(190, 230, 201, 16))
        self.sharpnessValDisplay.setStyleSheet("QProgressBar {\n"
"     border: 2px solid grey;\n"
"     border-radius: 5px;\n"
"     background-color: rgb(229, 229, 229);\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: rgb(90, 37, 255);;\n"
"     width: 20px;\n"
"    font-size: 0px;\n"
" }")
        self.sharpnessValDisplay.setProperty("value", 24)
        self.sharpnessValDisplay.setObjectName("sharpnessValDisplay")
        self.contrastLabel = QtWidgets.QLabel(editBmode)
        self.contrastLabel.setGeometry(QtCore.QRect(10, 100, 71, 41))
        self.contrastLabel.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.contrastLabel.setTextFormat(QtCore.Qt.AutoText)
        self.contrastLabel.setScaledContents(False)
        self.contrastLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.contrastLabel.setWordWrap(True)
        self.contrastLabel.setObjectName("contrastLabel")
        self.brightnessLabel = QtWidgets.QLabel(editBmode)
        self.brightnessLabel.setGeometry(QtCore.QRect(10, 160, 151, 41))
        self.brightnessLabel.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.brightnessLabel.setTextFormat(QtCore.Qt.AutoText)
        self.brightnessLabel.setScaledContents(False)
        self.brightnessLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.brightnessLabel.setWordWrap(True)
        self.brightnessLabel.setObjectName("brightnessLabel")
        self.sharpnessLabel = QtWidgets.QLabel(editBmode)
        self.sharpnessLabel.setGeometry(QtCore.QRect(10, 220, 151, 41))
        self.sharpnessLabel.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.sharpnessLabel.setTextFormat(QtCore.Qt.AutoText)
        self.sharpnessLabel.setScaledContents(False)
        self.sharpnessLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sharpnessLabel.setWordWrap(True)
        self.sharpnessLabel.setObjectName("sharpnessLabel")
        self.sharpnessVal = QtWidgets.QDoubleSpinBox(editBmode)
        self.sharpnessVal.setGeometry(QtCore.QRect(110, 230, 61, 21))
        self.sharpnessVal.setStyleSheet("QDoubleSpinBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"}")
        self.sharpnessVal.setMaximum(10.0)
        self.sharpnessVal.setObjectName("sharpnessVal")
        self.brightnessVal = QtWidgets.QDoubleSpinBox(editBmode)
        self.brightnessVal.setGeometry(QtCore.QRect(110, 170, 61, 21))
        self.brightnessVal.setStyleSheet("QDoubleSpinBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"}")
        self.brightnessVal.setMaximum(10.0)
        self.brightnessVal.setObjectName("brightnessVal")
        self.contrastVal = QtWidgets.QDoubleSpinBox(editBmode)
        self.contrastVal.setGeometry(QtCore.QRect(110, 110, 61, 21))
        self.contrastVal.setStyleSheet("QDoubleSpinBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"}")
        self.contrastVal.setMaximum(10.0)
        self.contrastVal.setObjectName("contrastVal")

        self.retranslateUi(editBmode)
        QtCore.QMetaObject.connectSlotsByName(editBmode)

    def retranslateUi(self, editBmode):
        _translate = QtCore.QCoreApplication.translate
        editBmode.setWindowTitle(_translate("editBmode", "Edit B-Mode Image"))
        self.editImageDisplayLabel.setText(_translate("editBmode", "Edit B-Mode Image Display"))
        self.contrastLabel.setText(_translate("editBmode", "Contrast"))
        self.brightnessLabel.setText(_translate("editBmode", "Brightness"))
        self.sharpnessLabel.setText(_translate("editBmode", "Sharpness"))
