# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UtcTool2d/loadRoi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loadRoi(object):
    def setupUi(self, loadRoi):
        loadRoi.setObjectName("loadRoi")
        loadRoi.resize(406, 324)
        loadRoi.setStyleSheet("QWidget {\n"
"    background-color: rgb(42, 42, 42);\n"
"}")
        self.editImageDisplayLabel = QtWidgets.QLabel(loadRoi)
        self.editImageDisplayLabel.setGeometry(QtCore.QRect(100, -30, 201, 131))
        self.editImageDisplayLabel.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.editImageDisplayLabel.setTextFormat(QtCore.Qt.AutoText)
        self.editImageDisplayLabel.setScaledContents(False)
        self.editImageDisplayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.editImageDisplayLabel.setWordWrap(True)
        self.editImageDisplayLabel.setObjectName("editImageDisplayLabel")
        self.newFolderPathLabel = QtWidgets.QLabel(loadRoi)
        self.newFolderPathLabel.setGeometry(QtCore.QRect(100, 50, 201, 51))
        self.newFolderPathLabel.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.newFolderPathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newFolderPathLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.newFolderPathLabel.setObjectName("newFolderPathLabel")
        self.roiPathInput = QtWidgets.QLineEdit(loadRoi)
        self.roiPathInput.setGeometry(QtCore.QRect(100, 100, 201, 31))
        self.roiPathInput.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.roiPathInput.setObjectName("roiPathInput")
        self.chooseFileButton = QtWidgets.QPushButton(loadRoi)
        self.chooseFileButton.setGeometry(QtCore.QRect(65, 140, 131, 41))
        self.chooseFileButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.chooseFileButton.setObjectName("chooseFileButton")
        self.clearFileButton = QtWidgets.QPushButton(loadRoi)
        self.clearFileButton.setGeometry(QtCore.QRect(205, 140, 131, 41))
        self.clearFileButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clearFileButton.setObjectName("clearFileButton")
        self.openRoiButton = QtWidgets.QPushButton(loadRoi)
        self.openRoiButton.setGeometry(QtCore.QRect(90, 210, 221, 41))
        self.openRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.openRoiButton.setObjectName("openRoiButton")
        self.backButton = QtWidgets.QPushButton(loadRoi)
        self.backButton.setGeometry(QtCore.QRect(90, 270, 221, 41))
        self.backButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.backButton.setObjectName("backButton")

        self.retranslateUi(loadRoi)
        QtCore.QMetaObject.connectSlotsByName(loadRoi)

    def retranslateUi(self, loadRoi):
        _translate = QtCore.QCoreApplication.translate
        loadRoi.setWindowTitle(_translate("loadRoi", "Load Region of Interest (ROI)"))
        self.editImageDisplayLabel.setText(_translate("loadRoi", "Load ROI:"))
        self.newFolderPathLabel.setText(_translate("loadRoi", "ROI file: (.csv)"))
        self.chooseFileButton.setText(_translate("loadRoi", "Choose File"))
        self.clearFileButton.setText(_translate("loadRoi", "Clear File"))
        self.openRoiButton.setText(_translate("loadRoi", "Open"))
        self.backButton.setText(_translate("loadRoi", "Back"))
