# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UtcTool2d/nameROI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_nameROI(object):
    def setupUi(self, nameROI):
        nameROI.setObjectName("nameROI")
        nameROI.resize(525, 368)
        nameROI.setStyleSheet("QWidget {\n"
"    background-color: rgb(42, 42, 42);\n"
"}")
        self.nameRoiLabel = QtWidgets.QLabel(nameROI)
        self.nameRoiLabel.setGeometry(QtCore.QRect(60, -20, 431, 131))
        self.nameRoiLabel.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.nameRoiLabel.setTextFormat(QtCore.Qt.AutoText)
        self.nameRoiLabel.setScaledContents(False)
        self.nameRoiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameRoiLabel.setWordWrap(True)
        self.nameRoiLabel.setObjectName("nameRoiLabel")
        self.nameRoiInput = QtWidgets.QLineEdit(nameROI)
        self.nameRoiInput.setGeometry(QtCore.QRect(230, 130, 271, 31))
        self.nameRoiInput.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"}")
        self.nameRoiInput.setObjectName("nameRoiInput")
        self.nameRoiPrompt = QtWidgets.QLabel(nameROI)
        self.nameRoiPrompt.setGeometry(QtCore.QRect(-20, 120, 271, 51))
        self.nameRoiPrompt.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.nameRoiPrompt.setAlignment(QtCore.Qt.AlignCenter)
        self.nameRoiPrompt.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.nameRoiPrompt.setObjectName("nameRoiPrompt")
        self.nameRoiContinueButton = QtWidgets.QPushButton(nameROI)
        self.nameRoiContinueButton.setGeometry(QtCore.QRect(200, 230, 131, 41))
        self.nameRoiContinueButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.nameRoiContinueButton.setObjectName("nameRoiContinueButton")
        self.nameRoiErrorMsg = QtWidgets.QLabel(nameROI)
        self.nameRoiErrorMsg.setGeometry(QtCore.QRect(210, 290, 111, 41))
        self.nameRoiErrorMsg.setStyleSheet("QLabel {\n"
"    color: rgb(255, 0, 23);\n"
"    font-size: 21px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.nameRoiErrorMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.nameRoiErrorMsg.setObjectName("nameRoiErrorMsg")

        self.retranslateUi(nameROI)
        QtCore.QMetaObject.connectSlotsByName(nameROI)

    def retranslateUi(self, nameROI):
        _translate = QtCore.QCoreApplication.translate
        nameROI.setWindowTitle(_translate("nameROI", "Name Region of Interest"))
        self.nameRoiLabel.setText(_translate("nameROI", "Name Region of Interest:"))
        self.nameRoiPrompt.setText(_translate("nameROI", "ROI Name:"))
        self.nameRoiContinueButton.setText(_translate("nameROI", "Continue"))
        self.nameRoiErrorMsg.setText(_translate("nameROI", "Error Msg"))
