# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UtcTool2d/psGraphDisplay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_psGraphWidget(object):
    def setupUi(self, psGraphWidget):
        psGraphWidget.setObjectName("psGraphWidget")
        psGraphWidget.resize(400, 300)
        psGraphWidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(42, 42, 42);\n"
"}")
        self.psGraphLabel = QtWidgets.QLabel(psGraphWidget)
        self.psGraphLabel.setGeometry(QtCore.QRect(-10, -30, 431, 131))
        self.psGraphLabel.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.psGraphLabel.setTextFormat(QtCore.Qt.AutoText)
        self.psGraphLabel.setScaledContents(False)
        self.psGraphLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.psGraphLabel.setWordWrap(True)
        self.psGraphLabel.setObjectName("psGraphLabel")
        self.psGraphFrame = QtWidgets.QFrame(psGraphWidget)
        self.psGraphFrame.setGeometry(QtCore.QRect(60, 80, 281, 191))
        self.psGraphFrame.setToolTipDuration(10)
        self.psGraphFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.psGraphFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.psGraphFrame.setObjectName("psGraphFrame")

        self.retranslateUi(psGraphWidget)
        QtCore.QMetaObject.connectSlotsByName(psGraphWidget)

    def retranslateUi(self, psGraphWidget):
        _translate = QtCore.QCoreApplication.translate
        psGraphWidget.setWindowTitle(_translate("psGraphWidget", "Power Spectrum Graph"))
        self.psGraphLabel.setText(_translate("psGraphWidget", "Power Spectrum Graph:"))
