# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UtcTool2d/rfAnalysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rfAnalysis(object):
    def setupUi(self, rfAnalysis):
        rfAnalysis.setObjectName("rfAnalysis")
        rfAnalysis.resize(1175, 749)
        rfAnalysis.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.widget = QtWidgets.QWidget(rfAnalysis)
        self.widget.setGeometry(QtCore.QRect(0, 0, 341, 751))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.widget.setObjectName("widget")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.label.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(-60, 40, 191, 51))
        self.label_2.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(-50, 70, 191, 51))
        self.label_3.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.imagePathInput = QtWidgets.QLabel(self.frame)
        self.imagePathInput.setGeometry(QtCore.QRect(100, 40, 241, 51))
        self.imagePathInput.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.imagePathInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.imagePathInput.setObjectName("imagePathInput")
        self.phantomPathInput = QtWidgets.QLabel(self.frame)
        self.phantomPathInput.setGeometry(QtCore.QRect(100, 70, 241, 51))
        self.phantomPathInput.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.phantomPathInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.phantomPathInput.setObjectName("phantomPathInput")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);;\n"
"    border: 1px solid black;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(0, 40, 341, 51))
        self.label_4.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.frame_4 = QtWidgets.QFrame(self.widget)
        self.frame_4.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.frame_4.setStyleSheet("QFrame {\n"
"    background-color:  rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.label_7.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.frame_5 = QtWidgets.QFrame(self.widget)
        self.frame_5.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.frame_5.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.label_8.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.saveRoiButton = QtWidgets.QPushButton(self.widget)
        self.saveRoiButton.setGeometry(QtCore.QRect(150, 690, 181, 41))
        self.saveRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.saveRoiButton.setObjectName("saveRoiButton")
        self.frame_3 = QtWidgets.QFrame(rfAnalysis)
        self.frame_3.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.frame_3.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.label_6.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.displayMbfButton = QtWidgets.QPushButton(rfAnalysis)
        self.displayMbfButton.setGeometry(QtCore.QRect(360, 120, 181, 41))
        self.displayMbfButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.displayMbfButton.setObjectName("displayMbfButton")
        self.displaySsButton = QtWidgets.QPushButton(rfAnalysis)
        self.displaySsButton.setGeometry(QtCore.QRect(560, 120, 181, 41))
        self.displaySsButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.displaySsButton.setObjectName("displaySsButton")
        self.displaySiButton = QtWidgets.QPushButton(rfAnalysis)
        self.displaySiButton.setGeometry(QtCore.QRect(760, 120, 181, 41))
        self.displaySiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.displaySiButton.setObjectName("displaySiButton")
        self.editImageDisplayButton = QtWidgets.QPushButton(rfAnalysis)
        self.editImageDisplayButton.setGeometry(QtCore.QRect(560, 700, 181, 41))
        self.editImageDisplayButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.editImageDisplayButton.setObjectName("editImageDisplayButton")
        self.avMbfLabel = QtWidgets.QLabel(rfAnalysis)
        self.avMbfLabel.setGeometry(QtCore.QRect(720, 0, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avMbfLabel.setFont(font)
        self.avMbfLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.avMbfLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.avMbfLabel.setObjectName("avMbfLabel")
        self.avSsLabel = QtWidgets.QLabel(rfAnalysis)
        self.avSsLabel.setGeometry(QtCore.QRect(720, 35, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avSsLabel.setFont(font)
        self.avSsLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.avSsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.avSsLabel.setObjectName("avSsLabel")
        self.avSiLabel = QtWidgets.QLabel(rfAnalysis)
        self.avSiLabel.setGeometry(QtCore.QRect(720, 70, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avSiLabel.setFont(font)
        self.avSiLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.avSiLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.avSiLabel.setObjectName("avSiLabel")
        self.avMbfVal = QtWidgets.QLabel(rfAnalysis)
        self.avMbfVal.setGeometry(QtCore.QRect(820, 0, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avMbfVal.setFont(font)
        self.avMbfVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.avMbfVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.avMbfVal.setObjectName("avMbfVal")
        self.avSsVal = QtWidgets.QLabel(rfAnalysis)
        self.avSsVal.setGeometry(QtCore.QRect(820, 35, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avSsVal.setFont(font)
        self.avSsVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.avSsVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.avSsVal.setObjectName("avSsVal")
        self.avSiVal = QtWidgets.QLabel(rfAnalysis)
        self.avSiVal.setGeometry(QtCore.QRect(820, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avSiVal.setFont(font)
        self.avSiVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.avSiVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.avSiVal.setObjectName("avSiVal")
        self.indSiVal = QtWidgets.QLabel(rfAnalysis)
        self.indSiVal.setGeometry(QtCore.QRect(970, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indSiVal.setFont(font)
        self.indSiVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indSiVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indSiVal.setObjectName("indSiVal")
        self.indMbfVal = QtWidgets.QLabel(rfAnalysis)
        self.indMbfVal.setGeometry(QtCore.QRect(970, 0, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indMbfVal.setFont(font)
        self.indMbfVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indMbfVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indMbfVal.setObjectName("indMbfVal")
        self.indMbfLabel = QtWidgets.QLabel(rfAnalysis)
        self.indMbfLabel.setGeometry(QtCore.QRect(870, 0, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indMbfLabel.setFont(font)
        self.indMbfLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indMbfLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indMbfLabel.setObjectName("indMbfLabel")
        self.indSiLabel = QtWidgets.QLabel(rfAnalysis)
        self.indSiLabel.setGeometry(QtCore.QRect(870, 70, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indSiLabel.setFont(font)
        self.indSiLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indSiLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indSiLabel.setObjectName("indSiLabel")
        self.indSsVal = QtWidgets.QLabel(rfAnalysis)
        self.indSsVal.setGeometry(QtCore.QRect(970, 35, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indSsVal.setFont(font)
        self.indSsVal.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indSsVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indSsVal.setObjectName("indSsVal")
        self.indSsLabel = QtWidgets.QLabel(rfAnalysis)
        self.indSsLabel.setGeometry(QtCore.QRect(870, 35, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.indSsLabel.setFont(font)
        self.indSsLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.indSsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.indSsLabel.setObjectName("indSsLabel")
        self.chooseWindowButton = QtWidgets.QPushButton(rfAnalysis)
        self.chooseWindowButton.setGeometry(QtCore.QRect(350, 700, 181, 41))
        self.chooseWindowButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.chooseWindowButton.setObjectName("chooseWindowButton")
        self.legend = QtWidgets.QFrame(rfAnalysis)
        self.legend.setGeometry(QtCore.QRect(1040, 20, 111, 131))
        self.legend.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.legend.setFrameShadow(QtWidgets.QFrame.Raised)
        self.legend.setObjectName("legend")
        self.constructRoiLabel = QtWidgets.QLabel(rfAnalysis)
        self.constructRoiLabel.setGeometry(QtCore.QRect(310, -10, 431, 131))
        self.constructRoiLabel.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.constructRoiLabel.setTextFormat(QtCore.Qt.AutoText)
        self.constructRoiLabel.setScaledContents(False)
        self.constructRoiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.constructRoiLabel.setWordWrap(True)
        self.constructRoiLabel.setObjectName("constructRoiLabel")
        self.backButton = QtWidgets.QPushButton(rfAnalysis)
        self.backButton.setGeometry(QtCore.QRect(10, 690, 131, 41))
        self.backButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.backButton.setObjectName("backButton")
        self.imDisplayFrame = QtWidgets.QFrame(rfAnalysis)
        self.imDisplayFrame.setGeometry(QtCore.QRect(400, 180, 721, 501))
        self.imDisplayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imDisplayFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imDisplayFrame.setObjectName("imDisplayFrame")
        self.saveDataButton = QtWidgets.QPushButton(rfAnalysis)
        self.saveDataButton.setGeometry(QtCore.QRect(770, 700, 181, 41))
        self.saveDataButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.saveDataButton.setObjectName("saveDataButton")
        self.exportDataButton = QtWidgets.QPushButton(rfAnalysis)
        self.exportDataButton.setGeometry(QtCore.QRect(980, 700, 181, 41))
        self.exportDataButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 12px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}")
        self.exportDataButton.setObjectName("exportDataButton")

        self.retranslateUi(rfAnalysis)
        QtCore.QMetaObject.connectSlotsByName(rfAnalysis)

    def retranslateUi(self, rfAnalysis):
        _translate = QtCore.QCoreApplication.translate
        rfAnalysis.setWindowTitle(_translate("rfAnalysis", "Radio Frequency Data Analysis"))
        self.widget.setToolTip(_translate("rfAnalysis", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("rfAnalysis", "Image Selection:"))
        self.label_2.setText(_translate("rfAnalysis", "Image:"))
        self.label_3.setText(_translate("rfAnalysis", "Phantom:"))
        self.imagePathInput.setText(_translate("rfAnalysis", "Sample filename "))
        self.phantomPathInput.setText(_translate("rfAnalysis", "Sample filename "))
        self.label_4.setText(_translate("rfAnalysis", "Region of Interest (ROI) Selection"))
        self.label_7.setText(_translate("rfAnalysis", "Radio Frequency Data Analysis"))
        self.label_8.setText(_translate("rfAnalysis", "Export Results"))
        self.saveRoiButton.setText(_translate("rfAnalysis", "Save ROI"))
        self.label_6.setText(_translate("rfAnalysis", "Analysis Parameter Selection"))
        self.displayMbfButton.setText(_translate("rfAnalysis", "Display Midband Fit (MBF)"))
        self.displaySsButton.setText(_translate("rfAnalysis", "Display Spectral Slope (SS)"))
        self.displaySiButton.setText(_translate("rfAnalysis", "Display Spectral Intercept (SI)"))
        self.editImageDisplayButton.setText(_translate("rfAnalysis", "Edit Image Display"))
        self.avMbfLabel.setText(_translate("rfAnalysis", "Av.  MBF"))
        self.avSsLabel.setText(_translate("rfAnalysis", "Av.  SS (1e-6)"))
        self.avSiLabel.setText(_translate("rfAnalysis", "Av.  SI"))
        self.avMbfVal.setText(_translate("rfAnalysis", "0"))
        self.avSsVal.setText(_translate("rfAnalysis", "0"))
        self.avSiVal.setText(_translate("rfAnalysis", "0"))
        self.indSiVal.setText(_translate("rfAnalysis", "0"))
        self.indMbfVal.setText(_translate("rfAnalysis", "0"))
        self.indMbfLabel.setText(_translate("rfAnalysis", "Ind.  MBF"))
        self.indSiLabel.setText(_translate("rfAnalysis", "Ind.  SI"))
        self.indSsVal.setText(_translate("rfAnalysis", "0"))
        self.indSsLabel.setText(_translate("rfAnalysis", "Ind.  SS (1e-6)"))
        self.chooseWindowButton.setText(_translate("rfAnalysis", "Choose Window to Analyze"))
        self.constructRoiLabel.setText(_translate("rfAnalysis", "Radio Frequency Analysis:"))
        self.backButton.setText(_translate("rfAnalysis", "Back"))
        self.saveDataButton.setText(_translate("rfAnalysis", "Save Data"))
        self.exportDataButton.setText(_translate("rfAnalysis", "Export Data"))
