# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UtcTool2d/selectImage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_selectImage(object):
    def setupUi(self, selectImage):
        selectImage.setObjectName("selectImage")
        selectImage.resize(1175, 749)
        selectImage.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.selectDataLabel = QtWidgets.QLabel(selectImage)
        self.selectDataLabel.setGeometry(QtCore.QRect(540, 100, 431, 131))
        self.selectDataLabel.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.selectDataLabel.setTextFormat(QtCore.Qt.AutoText)
        self.selectDataLabel.setScaledContents(False)
        self.selectDataLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.selectDataLabel.setWordWrap(True)
        self.selectDataLabel.setObjectName("selectDataLabel")
        self.phantomPathLabel = QtWidgets.QLabel(selectImage)
        self.phantomPathLabel.setGeometry(QtCore.QRect(790, 290, 271, 51))
        self.phantomPathLabel.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.phantomPathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.phantomPathLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.phantomPathLabel.setObjectName("phantomPathLabel")
        self.choosePhantomFileButton = QtWidgets.QPushButton(selectImage)
        self.choosePhantomFileButton.setGeometry(QtCore.QRect(792, 390, 131, 41))
        self.choosePhantomFileButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.choosePhantomFileButton.setObjectName("choosePhantomFileButton")
        self.phantomPathInput = QtWidgets.QLineEdit(selectImage)
        self.phantomPathInput.setGeometry(QtCore.QRect(820, 350, 201, 31))
        self.phantomPathInput.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.phantomPathInput.setObjectName("phantomPathInput")
        self.clearPhantomPathButton = QtWidgets.QPushButton(selectImage)
        self.clearPhantomPathButton.setGeometry(QtCore.QRect(930, 390, 131, 41))
        self.clearPhantomPathButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clearPhantomPathButton.setObjectName("clearPhantomPathButton")
        self.imagePathLabel = QtWidgets.QLabel(selectImage)
        self.imagePathLabel.setGeometry(QtCore.QRect(440, 290, 271, 51))
        self.imagePathLabel.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.imagePathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imagePathLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.imagePathLabel.setObjectName("imagePathLabel")
        self.chooseImageFileButton = QtWidgets.QPushButton(selectImage)
        self.chooseImageFileButton.setGeometry(QtCore.QRect(442, 390, 131, 41))
        self.chooseImageFileButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.chooseImageFileButton.setObjectName("chooseImageFileButton")
        self.imagePathInput = QtWidgets.QLineEdit(selectImage)
        self.imagePathInput.setGeometry(QtCore.QRect(470, 350, 201, 31))
        self.imagePathInput.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.imagePathInput.setObjectName("imagePathInput")
        self.clearImagePathButton = QtWidgets.QPushButton(selectImage)
        self.clearImagePathButton.setGeometry(QtCore.QRect(580, 390, 131, 41))
        self.clearImagePathButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clearImagePathButton.setObjectName("clearImagePathButton")
        self.generateImageButton = QtWidgets.QPushButton(selectImage)
        self.generateImageButton.setGeometry(QtCore.QRect(690, 510, 131, 41))
        self.generateImageButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.generateImageButton.setObjectName("generateImageButton")
        self.selectImageErrorMsg = QtWidgets.QLabel(selectImage)
        self.selectImageErrorMsg.setGeometry(QtCore.QRect(550, 590, 421, 81))
        self.selectImageErrorMsg.setStyleSheet("QLabel {\n"
"    color: rgb(255, 0, 23);\n"
"    font-size: 20px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.selectImageErrorMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.selectImageErrorMsg.setObjectName("selectImageErrorMsg")
        self.philipsButton = QtWidgets.QPushButton(selectImage)
        self.philipsButton.setGeometry(QtCore.QRect(590, 270, 301, 51))
        self.philipsButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.philipsButton.setObjectName("philipsButton")
        self.sidebar = QtWidgets.QWidget(selectImage)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 341, 751))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.imageSelectionSidebar = QtWidgets.QFrame(self.sidebar)
        self.imageSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.imageSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.imageSelectionSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageSelectionSidebar.setObjectName("imageSelectionSidebar")
        self.imageSelectionLabelSidebar = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imageSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.imageSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignCenter)
        self.imageSelectionLabelSidebar.setObjectName("imageSelectionLabelSidebar")
        self.imageLabel = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imageLabel.setGeometry(QtCore.QRect(-60, 40, 191, 51))
        self.imageLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.phantomLabel = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.phantomLabel.setGeometry(QtCore.QRect(-50, 70, 191, 51))
        self.phantomLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold\n"
"}")
        self.phantomLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.phantomLabel.setObjectName("phantomLabel")
        self.imageFilenameDisplay = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imageFilenameDisplay.setGeometry(QtCore.QRect(100, 40, 241, 51))
        self.imageFilenameDisplay.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.imageFilenameDisplay.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.imageFilenameDisplay.setObjectName("imageFilenameDisplay")
        self.phantomFilenameDisplay = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.phantomFilenameDisplay.setGeometry(QtCore.QRect(100, 70, 241, 51))
        self.phantomFilenameDisplay.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.phantomFilenameDisplay.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.phantomFilenameDisplay.setObjectName("phantomFilenameDisplay")
        self.roiSidebar = QtWidgets.QFrame(self.sidebar)
        self.roiSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.roiSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.roiSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.roiSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.roiSidebar.setObjectName("roiSidebar")
        self.roiSidebarLabel = QtWidgets.QLabel(self.roiSidebar)
        self.roiSidebarLabel.setGeometry(QtCore.QRect(0, 40, 341, 51))
        self.roiSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.roiSidebarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.roiSidebarLabel.setObjectName("roiSidebarLabel")
        self.rfAnalysisSidebar = QtWidgets.QFrame(self.sidebar)
        self.rfAnalysisSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.rfAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.rfAnalysisSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rfAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rfAnalysisSidebar.setObjectName("rfAnalysisSidebar")
        self.rfAnalysisLabel = QtWidgets.QLabel(self.rfAnalysisSidebar)
        self.rfAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.rfAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.rfAnalysisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rfAnalysisLabel.setObjectName("rfAnalysisLabel")
        self.exportResultsSidebar = QtWidgets.QFrame(self.sidebar)
        self.exportResultsSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.exportResultsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.exportResultsSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.exportResultsSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exportResultsSidebar.setObjectName("exportResultsSidebar")
        self.exportResultsLabel = QtWidgets.QLabel(self.exportResultsSidebar)
        self.exportResultsLabel.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.exportResultsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.exportResultsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.exportResultsLabel.setObjectName("exportResultsLabel")
        self.backButton = QtWidgets.QPushButton(self.sidebar)
        self.backButton.setGeometry(QtCore.QRect(10, 690, 131, 41))
        self.backButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.backButton.setObjectName("backButton")
        self.analysisParamsSidebar = QtWidgets.QFrame(selectImage)
        self.analysisParamsSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisParamsSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisParamsSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.analysisParamsSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.analysisParamsSidebar.setObjectName("analysisParamsSidebar")
        self.analysisParamsLabel = QtWidgets.QLabel(self.analysisParamsSidebar)
        self.analysisParamsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisParamsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisParamsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.analysisParamsLabel.setObjectName("analysisParamsLabel")
        self.transducerBrandLabel = QtWidgets.QLabel(selectImage)
        self.transducerBrandLabel.setGeometry(QtCore.QRect(540, 70, 431, 131))
        self.transducerBrandLabel.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.transducerBrandLabel.setTextFormat(QtCore.Qt.AutoText)
        self.transducerBrandLabel.setScaledContents(False)
        self.transducerBrandLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.transducerBrandLabel.setWordWrap(True)
        self.transducerBrandLabel.setObjectName("transducerBrandLabel")
        self.siemensButton = QtWidgets.QPushButton(selectImage)
        self.siemensButton.setGeometry(QtCore.QRect(590, 390, 301, 51))
        self.siemensButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.siemensButton.setObjectName("siemensButton")
        self.terasonButton = QtWidgets.QPushButton(selectImage)
        self.terasonButton.setGeometry(QtCore.QRect(590, 520, 301, 51))
        self.terasonButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.terasonButton.setObjectName("terasonButton")

        self.retranslateUi(selectImage)
        QtCore.QMetaObject.connectSlotsByName(selectImage)

    def retranslateUi(self, selectImage):
        _translate = QtCore.QCoreApplication.translate
        selectImage.setWindowTitle(_translate("selectImage", "Select Ultrasound Image"))
        self.selectDataLabel.setText(_translate("selectImage", "Select Data and Phantom Files to Generate Ultrasound Image:"))
        self.phantomPathLabel.setText(_translate("selectImage", "Input Path to Phantom file\n"
" (.rf, .rfd, .mat, .bin)"))
        self.choosePhantomFileButton.setText(_translate("selectImage", "Choose File"))
        self.clearPhantomPathButton.setText(_translate("selectImage", "Clear Path"))
        self.imagePathLabel.setText(_translate("selectImage", "Input Path to Image file\n"
" (.rf, .rfd, .mat, .bin)"))
        self.chooseImageFileButton.setText(_translate("selectImage", "Choose File"))
        self.clearImagePathButton.setText(_translate("selectImage", "Clear Path"))
        self.generateImageButton.setText(_translate("selectImage", "Generate Image"))
        self.selectImageErrorMsg.setText(_translate("selectImage", "ERROR: At least one dimension of phantom data\n"
"smaller than corresponding dimension\n"
"of image data"))
        self.philipsButton.setToolTip(_translate("selectImage", "<html><head/><body><p><br/></p></body></html>"))
        self.philipsButton.setText(_translate("selectImage", "Philips"))
        self.sidebar.setToolTip(_translate("selectImage", "<html><head/><body><p><br/></p></body></html>"))
        self.imageSelectionLabelSidebar.setText(_translate("selectImage", "Image Selection:"))
        self.imageLabel.setText(_translate("selectImage", "Image:"))
        self.phantomLabel.setText(_translate("selectImage", "Phantom:"))
        self.imageFilenameDisplay.setText(_translate("selectImage", "Sample filename "))
        self.phantomFilenameDisplay.setText(_translate("selectImage", "Sample filename "))
        self.roiSidebarLabel.setText(_translate("selectImage", "Region of Interest (ROI) Selection"))
        self.rfAnalysisLabel.setText(_translate("selectImage", "Radio Frequency Data Analysis"))
        self.exportResultsLabel.setText(_translate("selectImage", "Export Results"))
        self.backButton.setText(_translate("selectImage", "Back"))
        self.analysisParamsLabel.setText(_translate("selectImage", "Analysis Parameter Selection"))
        self.transducerBrandLabel.setText(_translate("selectImage", "Select Transducer Brand:"))
        self.siemensButton.setToolTip(_translate("selectImage", "<html><head/><body><p><br/></p></body></html>"))
        self.siemensButton.setText(_translate("selectImage", "Siemens"))
        self.terasonButton.setToolTip(_translate("selectImage", "<html><head/><body><p><br/></p></body></html>"))
        self.terasonButton.setText(_translate("selectImage", "Terason"))
