# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UtcTool2dIQ/roiSelection.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_constructRoi(object):
    def setupUi(self, constructRoi):
        constructRoi.setObjectName("constructRoi")
        constructRoi.resize(1175, 749)
        constructRoi.setStyleSheet("QWidget {\n"
"    background: rgb(42, 42, 42);\n"
"}")
        self.constructRoiLabel = QtWidgets.QLabel(constructRoi)
        self.constructRoiLabel.setGeometry(QtCore.QRect(550, -20, 431, 131))
        self.constructRoiLabel.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.constructRoiLabel.setTextFormat(QtCore.Qt.AutoText)
        self.constructRoiLabel.setScaledContents(False)
        self.constructRoiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.constructRoiLabel.setWordWrap(True)
        self.constructRoiLabel.setObjectName("constructRoiLabel")
        self.imDisplayFrame = QtWidgets.QFrame(constructRoi)
        self.imDisplayFrame.setGeometry(QtCore.QRect(400, 190, 721, 501))
        self.imDisplayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imDisplayFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imDisplayFrame.setObjectName("imDisplayFrame")
        self.drawRoiButton = QtWidgets.QPushButton(constructRoi)
        self.drawRoiButton.setGeometry(QtCore.QRect(370, 110, 171, 41))
        self.drawRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:checked {\n"
"    color:white; \n"
"    font-size: 16px;\n"
"    background: rgb(45, 0, 110);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.drawRoiButton.setCheckable(True)
        self.drawRoiButton.setChecked(False)
        self.drawRoiButton.setObjectName("drawRoiButton")
        self.undoLastPtButton = QtWidgets.QPushButton(constructRoi)
        self.undoLastPtButton.setGeometry(QtCore.QRect(570, 110, 171, 41))
        self.undoLastPtButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.undoLastPtButton.setCheckable(False)
        self.undoLastPtButton.setObjectName("undoLastPtButton")
        self.acceptRoiButton = QtWidgets.QPushButton(constructRoi)
        self.acceptRoiButton.setGeometry(QtCore.QRect(970, 110, 171, 41))
        self.acceptRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.acceptRoiButton.setCheckable(False)
        self.acceptRoiButton.setObjectName("acceptRoiButton")
        self.sidebar = QtWidgets.QWidget(constructRoi)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 341, 751))
        self.sidebar.setStyleSheet("QWidget {\n"
"    background-color: rgb(28, 0, 101);\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.imageSelectionSidebar = QtWidgets.QFrame(self.sidebar)
        self.imageSelectionSidebar.setGeometry(QtCore.QRect(0, 0, 341, 121))
        self.imageSelectionSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.imageSelectionSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageSelectionSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageSelectionSidebar.setObjectName("imageSelectionSidebar")
        self.imageSelectionLabelSidebar = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imageSelectionLabelSidebar.setGeometry(QtCore.QRect(70, 0, 191, 51))
        self.imageSelectionLabelSidebar.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageSelectionLabelSidebar.setAlignment(QtCore.Qt.AlignCenter)
        self.imageSelectionLabelSidebar.setObjectName("imageSelectionLabelSidebar")
        self.imageLabel = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imageLabel.setGeometry(QtCore.QRect(-60, 40, 191, 51))
        self.imageLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.phantomLabel = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.phantomLabel.setGeometry(QtCore.QRect(-50, 70, 191, 51))
        self.phantomLabel.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold\n"
"}")
        self.phantomLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.phantomLabel.setObjectName("phantomLabel")
        self.imagePathInput = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.imagePathInput.setGeometry(QtCore.QRect(100, 40, 241, 51))
        self.imagePathInput.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.imagePathInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.imagePathInput.setObjectName("imagePathInput")
        self.phantomPathInput = QtWidgets.QLabel(self.imageSelectionSidebar)
        self.phantomPathInput.setGeometry(QtCore.QRect(100, 70, 241, 51))
        self.phantomPathInput.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.phantomPathInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.phantomPathInput.setObjectName("phantomPathInput")
        self.roiSidebar = QtWidgets.QFrame(self.sidebar)
        self.roiSidebar.setGeometry(QtCore.QRect(0, 120, 341, 121))
        self.roiSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 0, 174);\n"
"    border: 1px solid black;\n"
"}")
        self.roiSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.roiSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.roiSidebar.setObjectName("roiSidebar")
        self.roiSidebarLabel = QtWidgets.QLabel(self.roiSidebar)
        self.roiSidebarLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.roiSidebarLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.roiSidebarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.roiSidebarLabel.setObjectName("roiSidebarLabel")
        self.rfAnalysisSidebar = QtWidgets.QFrame(self.sidebar)
        self.rfAnalysisSidebar.setGeometry(QtCore.QRect(0, 360, 341, 121))
        self.rfAnalysisSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.rfAnalysisSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rfAnalysisSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rfAnalysisSidebar.setObjectName("rfAnalysisSidebar")
        self.rfAnalysisLabel = QtWidgets.QLabel(self.rfAnalysisSidebar)
        self.rfAnalysisLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.rfAnalysisLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.rfAnalysisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rfAnalysisLabel.setObjectName("rfAnalysisLabel")
        self.exportResultsSidebar = QtWidgets.QFrame(self.sidebar)
        self.exportResultsSidebar.setGeometry(QtCore.QRect(0, 480, 341, 121))
        self.exportResultsSidebar.setStyleSheet("QFrame {\n"
"    background-color:  rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.exportResultsSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.exportResultsSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exportResultsSidebar.setObjectName("exportResultsSidebar")
        self.exportResultsLabel = QtWidgets.QLabel(self.exportResultsSidebar)
        self.exportResultsLabel.setGeometry(QtCore.QRect(20, 30, 301, 51))
        self.exportResultsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight: bold;\n"
"}")
        self.exportResultsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.exportResultsLabel.setObjectName("exportResultsLabel")
        self.analysisParamsSidebar = QtWidgets.QFrame(constructRoi)
        self.analysisParamsSidebar.setGeometry(QtCore.QRect(0, 240, 341, 121))
        self.analysisParamsSidebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(49, 0, 124);\n"
"    border: 1px solid black;\n"
"}")
        self.analysisParamsSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.analysisParamsSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.analysisParamsSidebar.setObjectName("analysisParamsSidebar")
        self.analysisParamsLabel = QtWidgets.QLabel(self.analysisParamsSidebar)
        self.analysisParamsLabel.setGeometry(QtCore.QRect(0, 30, 341, 51))
        self.analysisParamsLabel.setStyleSheet("QLabel {\n"
"    font-size: 21px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"    font-weight:bold;\n"
"}")
        self.analysisParamsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.analysisParamsLabel.setObjectName("analysisParamsLabel")
        self.editImageDisplayButton = QtWidgets.QPushButton(constructRoi)
        self.editImageDisplayButton.setGeometry(QtCore.QRect(940, 700, 181, 41))
        self.editImageDisplayButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.editImageDisplayButton.setObjectName("editImageDisplayButton")
        self.closeRoiButton = QtWidgets.QPushButton(constructRoi)
        self.closeRoiButton.setGeometry(QtCore.QRect(770, 110, 171, 41))
        self.closeRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.closeRoiButton.setCheckable(False)
        self.closeRoiButton.setObjectName("closeRoiButton")
        self.redrawRoiButton = QtWidgets.QPushButton(constructRoi)
        self.redrawRoiButton.setGeometry(QtCore.QRect(770, 110, 171, 41))
        self.redrawRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.redrawRoiButton.setCheckable(False)
        self.redrawRoiButton.setObjectName("redrawRoiButton")
        self.backButton = QtWidgets.QPushButton(constructRoi)
        self.backButton.setGeometry(QtCore.QRect(20, 690, 131, 41))
        self.backButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.backButton.setObjectName("backButton")
        self.undoLoadedRoiButton = QtWidgets.QPushButton(constructRoi)
        self.undoLoadedRoiButton.setGeometry(QtCore.QRect(420, 110, 271, 41))
        self.undoLoadedRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.undoLoadedRoiButton.setCheckable(True)
        self.undoLoadedRoiButton.setChecked(False)
        self.undoLoadedRoiButton.setObjectName("undoLoadedRoiButton")
        self.newRoiButton = QtWidgets.QPushButton(constructRoi)
        self.newRoiButton.setGeometry(QtCore.QRect(420, 110, 271, 41))
        self.newRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.newRoiButton.setCheckable(True)
        self.newRoiButton.setChecked(False)
        self.newRoiButton.setObjectName("newRoiButton")
        self.acceptLoadedRoiButton = QtWidgets.QPushButton(constructRoi)
        self.acceptLoadedRoiButton.setGeometry(QtCore.QRect(820, 110, 271, 41))
        self.acceptLoadedRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.acceptLoadedRoiButton.setCheckable(True)
        self.acceptLoadedRoiButton.setChecked(False)
        self.acceptLoadedRoiButton.setObjectName("acceptLoadedRoiButton")
        self.loadRoiButton = QtWidgets.QPushButton(constructRoi)
        self.loadRoiButton.setGeometry(QtCore.QRect(820, 110, 271, 41))
        self.loadRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.loadRoiButton.setCheckable(True)
        self.loadRoiButton.setChecked(False)
        self.loadRoiButton.setObjectName("loadRoiButton")

        self.retranslateUi(constructRoi)
        QtCore.QMetaObject.connectSlotsByName(constructRoi)

    def retranslateUi(self, constructRoi):
        _translate = QtCore.QCoreApplication.translate
        constructRoi.setWindowTitle(_translate("constructRoi", "Select Region of Interest"))
        self.constructRoiLabel.setText(_translate("constructRoi", "Construct Region of Interest (ROI):"))
        self.drawRoiButton.setText(_translate("constructRoi", "Draw ROI"))
        self.undoLastPtButton.setText(_translate("constructRoi", "Undo Last Point"))
        self.acceptRoiButton.setText(_translate("constructRoi", "Accept ROI"))
        self.sidebar.setToolTip(_translate("constructRoi", "<html><head/><body><p><br/></p></body></html>"))
        self.imageSelectionLabelSidebar.setText(_translate("constructRoi", "Image Selection:"))
        self.imageLabel.setText(_translate("constructRoi", "Image:"))
        self.phantomLabel.setText(_translate("constructRoi", "Phantom:"))
        self.imagePathInput.setText(_translate("constructRoi", "Sample filename "))
        self.phantomPathInput.setText(_translate("constructRoi", "Sample filename "))
        self.roiSidebarLabel.setText(_translate("constructRoi", "Region of Interest (ROI) Selection"))
        self.rfAnalysisLabel.setText(_translate("constructRoi", "Radio Frequency Data Analysis"))
        self.exportResultsLabel.setText(_translate("constructRoi", "Export Results"))
        self.analysisParamsLabel.setText(_translate("constructRoi", "Analysis Parameter Selection"))
        self.editImageDisplayButton.setText(_translate("constructRoi", "Edit Image Display"))
        self.closeRoiButton.setText(_translate("constructRoi", "Close ROI"))
        self.redrawRoiButton.setText(_translate("constructRoi", "Redraw ROI"))
        self.backButton.setText(_translate("constructRoi", "Back"))
        self.undoLoadedRoiButton.setText(_translate("constructRoi", "Undo"))
        self.newRoiButton.setText(_translate("constructRoi", "New ROI"))
        self.acceptLoadedRoiButton.setText(_translate("constructRoi", "Accept ROI"))
        self.loadRoiButton.setText(_translate("constructRoi", "Load ROI"))
