# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UtcTool2dIQ/saveRoi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_saveRoi(object):
    def setupUi(self, saveRoi):
        saveRoi.setObjectName("saveRoi")
        saveRoi.resize(633, 500)
        saveRoi.setStyleSheet("QWidget {\n"
"    background-color: rgb(42, 42, 42);\n"
"}")
        self.saveRoiLabel = QtWidgets.QLabel(saveRoi)
        self.saveRoiLabel.setGeometry(QtCore.QRect(210, -20, 201, 131))
        self.saveRoiLabel.setStyleSheet("QLabel {\n"
"    font-size: 29px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.saveRoiLabel.setTextFormat(QtCore.Qt.AutoText)
        self.saveRoiLabel.setScaledContents(False)
        self.saveRoiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.saveRoiLabel.setWordWrap(True)
        self.saveRoiLabel.setObjectName("saveRoiLabel")
        self.roiFolderPathLabel = QtWidgets.QLabel(saveRoi)
        self.roiFolderPathLabel.setGeometry(QtCore.QRect(210, 80, 201, 51))
        self.roiFolderPathLabel.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.roiFolderPathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.roiFolderPathLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.roiFolderPathLabel.setObjectName("roiFolderPathLabel")
        self.newFolderPathInput = QtWidgets.QLineEdit(saveRoi)
        self.newFolderPathInput.setGeometry(QtCore.QRect(210, 130, 201, 31))
        self.newFolderPathInput.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.newFolderPathInput.setObjectName("newFolderPathInput")
        self.chooseFolderButton = QtWidgets.QPushButton(saveRoi)
        self.chooseFolderButton.setGeometry(QtCore.QRect(175, 170, 131, 41))
        self.chooseFolderButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.chooseFolderButton.setObjectName("chooseFolderButton")
        self.clearFolderButton = QtWidgets.QPushButton(saveRoi)
        self.clearFolderButton.setGeometry(QtCore.QRect(315, 170, 131, 41))
        self.clearFolderButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clearFolderButton.setObjectName("clearFolderButton")
        self.saveRoiButton = QtWidgets.QPushButton(saveRoi)
        self.saveRoiButton.setGeometry(QtCore.QRect(200, 440, 221, 41))
        self.saveRoiButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    background: rgb(90, 37, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.saveRoiButton.setObjectName("saveRoiButton")
        self.dataSavedSuccessfullyLabel = QtWidgets.QLabel(saveRoi)
        self.dataSavedSuccessfullyLabel.setGeometry(QtCore.QRect(100, 190, 421, 81))
        self.dataSavedSuccessfullyLabel.setStyleSheet("QLabel {\n"
"    color: rgb(23, 255, 0);\n"
"    font-size: 30px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.dataSavedSuccessfullyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dataSavedSuccessfullyLabel.setObjectName("dataSavedSuccessfullyLabel")
        self.newFileNameLabel = QtWidgets.QLabel(saveRoi)
        self.newFileNameLabel.setGeometry(QtCore.QRect(170, 230, 271, 51))
        self.newFileNameLabel.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white;\n"
"    font-size: 17px;\n"
"}")
        self.newFileNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newFileNameLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.newFileNameLabel.setObjectName("newFileNameLabel")
        self.newFileNameInput = QtWidgets.QLineEdit(saveRoi)
        self.newFileNameInput.setGeometry(QtCore.QRect(210, 290, 201, 31))
        self.newFileNameInput.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(249, 249, 249);\n"
"    color: black;\n"
"}")
        self.newFileNameInput.setAlignment(QtCore.Qt.AlignCenter)
        self.newFileNameInput.setObjectName("newFileNameInput")
        self.fileNameErrorLabel = QtWidgets.QLabel(saveRoi)
        self.fileNameErrorLabel.setGeometry(QtCore.QRect(100, 320, 421, 81))
        self.fileNameErrorLabel.setStyleSheet("QLabel {\n"
"    color: rgb(255, 0, 23);\n"
"    font-size: 20px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.fileNameErrorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fileNameErrorLabel.setObjectName("fileNameErrorLabel")
        self.fileNameWarningLabel = QtWidgets.QLabel(saveRoi)
        self.fileNameWarningLabel.setGeometry(QtCore.QRect(100, 350, 421, 81))
        self.fileNameWarningLabel.setStyleSheet("QLabel {\n"
"    color: rgb(255, 0, 23);\n"
"    font-size: 20px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.fileNameWarningLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fileNameWarningLabel.setObjectName("fileNameWarningLabel")

        self.retranslateUi(saveRoi)
        QtCore.QMetaObject.connectSlotsByName(saveRoi)

    def retranslateUi(self, saveRoi):
        _translate = QtCore.QCoreApplication.translate
        saveRoi.setWindowTitle(_translate("saveRoi", "Save Region Of Interest (ROI)"))
        self.saveRoiLabel.setText(_translate("saveRoi", "Save ROI:"))
        self.roiFolderPathLabel.setText(_translate("saveRoi", "Folder to save ROI in:"))
        self.chooseFolderButton.setText(_translate("saveRoi", "Choose Folder"))
        self.clearFolderButton.setText(_translate("saveRoi", "Clear Folder"))
        self.saveRoiButton.setText(_translate("saveRoi", "Save"))
        self.dataSavedSuccessfullyLabel.setText(_translate("saveRoi", "ROI saved successfully!"))
        self.newFileNameLabel.setText(_translate("saveRoi", "Type name of new file:\n"
"(no spaces,  must end in \".csv\")"))
        self.fileNameErrorLabel.setText(_translate("saveRoi", "ERROR: Filename must not contain a space\n"
"and must end in \".csv\""))
        self.fileNameWarningLabel.setText(_translate("saveRoi", "WARNING: If file of specified folder and filename\n"
"already exists,  that file will be\n"
"deleted and overwritten"))
